// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=exe, use-js-string=true, version=6.0.1+6.0.1
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(c){"use strict";var
jc=typeof
module==="object"&&module.exports||c,dL="Sys_error",dM="readdir",Y=0x80,ai=" ",L="0",d7="ENOTEMPTY",ch="compare: functional value",cj="EEXIST",ce=1255,ak=1000,cg="mkdir",cc="open",eb="@[",a2="int_of_string",ca="e",dZ="%u",d0=" doesn't exist",ea="/static/",aY="ENOENT",d6="Stack_overflow",cl="node:fs",b7="load",dB="%i",dC="dir",ep="%ni",al=0xff,bp="no such file or directory",eg="Undefined_recursive_module",bm="lseek",b$="EISDIR",d$="Assert_failure",dY="not a directory",dA="0x",H=0x8000,dK=0x800,dX=0x7ff0,d5=-48,dq="error",dy="file already exists",dz=0xdfff,dI="@{",dJ="Division_by_zero",bu=0x7c00,az=".",dW="End_of_file",d4=0xfc00,aM=0x3f,en="Out_of_memory",eo="illegal operation on a directory",a0="bad file descriptor",em="win32",dx="Not_found",ck="Failure",ar=128,d3="truncate",el="Unix.Unix_error",dV="^",a1="invalid argument",dH=255,bq="ENOTDIR",ci=256,dG=100,b6="index out of bounds",d2="Lwt.",aj="/",dU="write",bl=252,dw="%Li",dv="Invalid_argument",bo=254,aL="+",b5="%d",ek=", characters ",ay="-",aJ="EBADF",U=0xffffff,d_=120,du=0x0400,d9=1027,aZ=1024,dT=1023,dF=-97,dS="Pervasives.do_at_exit",ef="Printexc.handle_uncaught_exception",dp=12520,dt="Lwt.%s",aK="EINVAL",dR=65536,d8=0.0009765625,cb=0xf,b_=", ",bn=512,dQ="read",d1="Fatal error: exception %s\n",ej="Match_failure",dr="%li",ds=1026,dn=250,b9="nan",e="",b8="rmdir",dE="([^/]+)",br="Fatal error: exception ",ee=0x7fffffff,dP="infinity",cd="jsError",a="camlinternalFormat.ml",dm=103,bk='"',dO="fd ",V=0xffff,bt=127,dD="illegal seek",ei=": ",dl=0xdc00,ed="Sys_blocked_io",ab=0x100,g=248,cf="ESPIPE",ec="_",eh=0xe0,dN=0xf0,bs="_bigarr02";function
ia(a,b,c,d,e){if(d<=b)for(var
f=1;f<=e;f++)c[d+f]=a[b+f];else
for(var
f=e;f>=1;f--)c[d+f]=a[b+f];return 0}var
e4={};function
je(a){if(e4[a])return e4[a];var
b=c.process;if(b&&b.env&&b.env[a]!==undefined)return b.env[a];if(c.jsoo_env&&typeof
c.jsoo_env[a]==="string")return c.jsoo_env[a]}var
bI=0;(function(){var
c=je("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]==="b"){bI=1;break}else if(b[a].startsWith("b="))bI=+b[a].slice(2);else
continue}}());var
i6=bI,z=[0];function
ir(a,b){if(!a.js_error||b||a[0]===g)a.js_error=new
c.Error("Js exception containing backtrace");return a}function
h(a,b){return bI&&i6?ir(a,b):a}function
eW(a,b){throw h([0,a,b])}function
an(a){return a}function
eY(a,b){eW(a,an(b))}function
k(a){eY(z.Invalid_argument,a)}function
a3(){k(b6)}function
es(a,b){if(a>>>0>=(ee/4|0))a3();var
a=a+1|0,c=new
Array(a);c[0]=0;for(var
d=1;d<a;d++)c[d]=b;return c}function
et(a,b,c){if(a[1]===b){a[1]=c;return 1}return 0}function
ib(a,b){var
c=a[1];a[1]+=b;return c}function
bv(a){return a[1]}function
ex(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
ev(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break;case
13:c=Uint16Array;break}if(!c)k("Bigarray.create: unsupported kind");var
d=new
c(b*ex(a));return d}function
bw(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)k("Bigarray.create: negative dimension");c=c*a[b]}return c}var
eT=function(){const
d=1/Number.EPSILON;function
k(a){return a+d-d}const
g=6.103515625e-5,j=65504,a=d8,f=a*g,i=a*d;function
l(a){const
b=+a;if(!Number.isFinite(b)||b===0)return b;const
e=b>0?1:-1,c=Math.abs(b);if(c<g)return e*k(c/f)*f;const
h=(1+i)*c,d=h-(h-c);if(d>j||Number.isNaN(d))return e*Number.POSITIVE_INFINITY;return e*d}const
b=new
Uint16Array(bn),c=new
Uint8Array(bn);for(let
a=0;a<ci;++a){const
d=a-bt;if(d<-24){b[a]=0x0000;b[a|ab]=H;c[a]=24;c[a|ab]=24}else if(d<-14){b[a]=du>>-d-14;b[a|ab]=du>>-d-14|H;c[a]=-d-1;c[a|ab]=-d-1}else if(d<=15){b[a]=d+15<<10;b[a|ab]=d+15<<10|H;c[a]=13;c[a|ab]=13}else if(d<ar){b[a]=bu;b[a|ab]=d4;c[a]=24;c[a|ab]=24}else{b[a]=bu;b[a|ab]=d4;c[a]=13;c[a|ab]=13}}const
e=new
ArrayBuffer(4),h=new
Float32Array(e),m=new
Uint32Array(e);return function(a){h[0]=l(a);const
e=m[0],d=e>>23&0x1ff;return b[d]+((e&0x007fffff)>>c[d])}}(),cH=function(){var
h=Math.pow,e=31,i=dT,f=h(2,-24),g=d8;return function(a){var
d=a>>>15,c=a>>>10&e,b=a&i;if(c===e)return b===0?d===0?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:Number.NaN;if(c===0)return b*(d===0?f:-f);var
j=h(2,c-15)*(d===0?1+b*g:-1-b*g);return j}}(),a9=Math.pow(2,-24);function
i5(a){throw a}function
eZ(){i5(z.Division_by_zero)}function
d(a,b,c){this.lo=a&U;this.mi=b&U;this.hi=c&V}d.prototype.caml_custom="_j";d.prototype.copy=function(){return new
d(this.lo,this.mi,this.hi)};d.prototype.ucompare=function(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};d.prototype.compare=function(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};d.prototype.neg=function(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
d(a,b,c)};d.prototype.add=function(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),e=this.hi+a.hi+(c>>24);return new
d(b,c,e)};d.prototype.sub=function(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),e=this.hi-a.hi+(c>>24);return new
d(b,c,e)};d.prototype.mul=function(a){var
b=this.lo*a.lo,c=(b*a9|0)+this.mi*a.lo+this.lo*a.mi,e=(c*a9|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
d(b,c,e)};d.prototype.isZero=function(){return(this.lo|this.mi|this.hi)===0};d.prototype.isNeg=function(){return this.hi<<16<0};d.prototype.and=function(a){return new
d(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)};d.prototype.or=function(a){return new
d(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)};d.prototype.xor=function(a){return new
d(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)};d.prototype.shift_left=function(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
d(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
d(0,0,this.lo<<a-48)};d.prototype.shift_right_unsigned=function(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
d(this.hi>>a-48,0,0)};d.prototype.shift_right=function(a){a=a&63;if(a===0)return this;var
c=this.hi<<16>>16;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,b&V);return new
d(this.hi<<16>>a-32,b,b)};d.prototype.lsl1=function(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&U;this.lo=this.lo<<1&U};d.prototype.lsr1=function(){this.lo=(this.lo>>>1|this.mi<<23)&U;this.mi=(this.mi>>>1|this.hi<<23)&U;this.hi=this.hi>>>1};d.prototype.udivmod=function(a){var
e=0,c=this.copy(),b=a.copy(),f=new
d(0,0,0);while(c.ucompare(b)>0){e++;b.lsl1()}while(e>=0){e--;f.lsl1();if(c.ucompare(b)>=0){f.lo++;c=c.sub(b)}b.lsr1()}return{quotient:f,modulus:c}};d.prototype.div=function(a){var
b=this;if(a.isZero())eZ();var
d=b.hi^a.hi;if(b.hi&H)b=b.neg();if(a.hi&H)a=a.neg();var
c=b.udivmod(a).quotient;if(d&H)c=c.neg();return c};d.prototype.mod=function(a){var
b=this;if(a.isZero())eZ();var
d=b.hi;if(b.hi&H)b=b.neg();if(a.hi&H)a=a.neg();var
c=b.udivmod(a).modulus;if(d&H)c=c.neg();return c};d.prototype.toInt=function(){return this.lo|this.mi<<24};d.prototype.toFloat=function(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo};d.prototype.toArray=function(){return[this.hi>>8,this.hi&al,this.mi>>16,this.mi>>8&al,this.mi&al,this.lo>>16,this.lo>>8&al,this.lo&al]};d.prototype.lo32=function(){return this.lo|(this.mi&al)<<24};d.prototype.hi32=function(){return this.mi>>>8&V|this.hi<<16};function
iA(a,b){return new
d(a&U,a>>>24&al|(b&V)<<8,b>>>16&V)}function
cv(a){return a.hi32()}function
cw(a){return a.lo32()}var
id=bs;function
at(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d}at.prototype.caml_custom=id;at.prototype.offset=function(a){var
c=0;if(typeof
a==="number")a=[a];if(!Array.isArray(a))k("bigarray.js: invalid offset");if(this.dims.length!==a.length)k("Bigarray.get/set: bad number of dimensions");if(this.layout===0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])a3();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])a3();c=c*this.dims[b]+(a[b]-1)}return c};at.prototype.get=function(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return iA(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[bo,e,c];case
13:return cH(this.data[a]);default:return this.data[a]}};at.prototype.set=function(a,b){switch(this.kind){case
7:this.data[a*2+0]=cw(b);this.data[a*2+1]=cv(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;case
13:this.data[a]=eT(b);break;default:this.data[a]=b;break}return 0};at.prototype.fill=function(a){switch(this.kind){case
7:var
c=cw(a),e=cv(a);if(c===e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d===f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?d:f;break;case
13:this.data.fill(eT(a));break;default:this.data.fill(a);break}};at.prototype.compare=function(a,b){if(this.layout!==a.layout||this.kind!==a.kind){var
h=this.kind|this.layout<<8,i=a.kind|a.layout<<8;return i-h}if(this.dims.length!==a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!==a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!==e){if(!b)return Number.NaN;if(!Number.isNaN(d))return 1;if(!Number.isNaN(e))return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
13:for(var
c=0;c<this.data.length;c++){var
f=cH(this.data[c]),g=cH(a.data[c]);if(f<g)return-1;if(f>g)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0};function
aN(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d}aN.prototype=new
at();aN.prototype.offset=function(a){if(typeof
a!=="number")if(Array.isArray(a)&&a.length===1)a=a[0];else
k("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])a3();return a};aN.prototype.get=function(a){return this.data[a]};aN.prototype.set=function(a,b){this.data[a]=b;return 0};aN.prototype.fill=function(a){this.data.fill(a);return 0};function
cm(a,b,c,d){var
e=ex(a);if(bw(c)*e!==d.length)k("length doesn't match dims");if(b===0&&c.length===1&&e===1&&a!==13)return new
aN(a,b,c,d);return new
at(a,b,c,d)}function
cA(a){return a.slice(1)}function
ic(a,b,c){var
d=cA(c),e=ev(a,bw(d));return cm(a,b,d,e)}function
a4(a,b,c){a.set(a.offset(b),c);return 0}function
bK(a,b,c){var
d=String.fromCharCode;if(b===0&&c<=4096&&c===a.length)return d.apply(null,a);var
f=e;for(;0<c;b+=aZ,c-=aZ)f+=d.apply(null,a.subarray(b,b+Math.min(c,aZ)));return f}function
by(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
au(a,b,c,d,e){if(e===0)return 0;if(d===0&&(e>=c.l||c.t===2&&e>=c.c.length)){c.c=a.t===4?bK(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else if(c.t===2&&d===c.c.length){c.c+=a.t===4?bK(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else{if(c.t!==4)by(c);var
g=a.c,h=c.c;if(a.t===4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aR(a,b){if(a===0)return e;if(b.repeat)return b.repeat(a);var
d=e,c=0;for(;;){if(a&1)d+=b;a>>=1;if(a===0)return d;b+=b;c++;if(c===9)b.slice(0,1)}}function
bz(a){if(a.t===2)a.c+=aR(a.l-a.c.length,"\0");else
a.c=bK(a.c,0,a.c.length);a.t=0}function
cJ(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>bt)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
e2(a){for(var
k=e,d=e,h,g,i,b,c=0,j=a.length;c<j;c++){g=a.charCodeAt(c);if(g<Y){for(var
f=c+1;f<j&&(g=a.charCodeAt(f))<Y;f++);if(f-c>bn){d.slice(0,1);k+=d;d=e;k+=a.slice(c,f)}else
d+=a.slice(c,f);if(f===j)break;c=f}b=1;if(++c<j&&((i=a.charCodeAt(c))&-64)===ar){h=i+(g<<6);if(g<eh){b=h-0x3080;if(b<Y)b=1}else{b=2;if(++c<j&&((i=a.charCodeAt(c))&-64)===ar){h=i+(h<<6);if(g<dN){b=h-0xe2080;if(b<dK||b>=0xd7ff&&b<0xe000)b=2}else{b=3;if(++c<j&&((i=a.charCodeAt(c))&-64)===ar&&g<0xf5){b=i-0x3c82080+(h<<6);if(b<0x10000||b>0x10ffff)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else if(b>V)d+=String.fromCharCode(0xd7c0+(b>>10),dl+(b&0x3ff));else
d+=String.fromCharCode(b);if(d.length>aZ){d.slice(0,1);k+=d;d=e}}return k+d}function
ac(a,b,c){this.t=a;this.c=b;this.l=c}ac.prototype.toString=function(){switch(this.t){case
9:case
8:return this.c;case
4:case
2:bz(this);case
0:if(cJ(this.c))this.t=9;else
this.t=8;return this.c}};ac.prototype.toUtf16=function(){var
a=this.toString();if(this.t===9)return a;return e2(a)};ac.prototype.slice=function(){var
a=this.t===4?this.c.slice():this.c;return new
ac(this.t,a,this.l)};function
eA(a){return new
ac(0,a,a.length)}function
aP(a){return a}function
aA(a){return eA(aP(a))}function
bx(a,b,c,d,e){au(aA(a),b,c,d,e);return 0}function
ih(){k(b6)}function
r(a,b,c){c&=al;if(a.t!==4){if(b===a.c.length){a.c+=String.fromCharCode(c);if(b+1===a.l)a.t=0;return 0}by(a)}a.c[b]=c;return 0}function
aB(a,b,c){if(b>>>0>=a.l)ih();return r(a,b,c)}function
cn(a,b){switch(a.t&6){case
0:return a.c.charCodeAt(b);case
2:if(b>=a.c.length)return 0;return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aC(c,e){var
f=c.l>=0?c.l:c.l=c.length,d=e.length,b=f-d;if(b===0)return c(...e);else if(b<0){var
a=c(...e.slice(0,f));if(typeof
a!=="function")return a;return aC(a,e.slice(f))}else{switch(b){case
1:{var
a=function(a){var
f=new
Array(d+1);for(var
b=0;b<d;b++)f[b]=e[b];f[d]=a;return c(...f)};break}case
2:{var
a=function(a,b){var
g=new
Array(d+2);for(var
f=0;f<d;f++)g[f]=e[f];g[d]=a;g[d+1]=b;return c(...g)};break}default:var
a=function(...a){if(a.length===0)a=[undefined];return aC(c,e.concat(a))}}a.l=b;return a}}function
a5(a,b){if(b>>>0>=a.length-1)a3();return a}function
ik(a){if(Number.isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!==0)return 1;return 2}return Number.isNaN(a)?4:3}function
im(){return[0]}function
D(a){if(a<0)k("Bytes.create");return new
ac(a?2:9,e,a)}var
bA=[0];function
ip(a,b){if(bA!==a)return 0;bA=b;return 1}function
eF(a){return bA}function
iq(a){bA=a}function
is(a,b,c,d){if(c>0)if(b===0&&(c>=a.l||a.t===2&&c>=a.c.length))if(d===0){a.c=e;a.t=2}else{a.c=aR(c,String.fromCharCode(d));a.t=c===a.l?0:2}else{if(a.t!==4)by(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
cF(a){a=aP(a);var
e=a.length;if(e>31)k("format_int: format too long");var
b={justify:aL,signstyle:ay,filler:ai,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=ay;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=L;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;break;case"d":case"i":b.signedconv=true;b.base=10;break;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}function
cp(a,b){if(a.uppercase)b=b.toUpperCase();var
f=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!==ay))f++;if(a.alternate){if(a.base===8)f+=1;if(a.base===16)f+=2}var
c=e;if(a.justify===aL&&a.filler===ai)for(var
d=f;d<a.width;d++)c+=ai;if(a.signedconv)if(a.sign<0)c+=ay;else if(a.signstyle!==ay)c+=a.signstyle;if(a.alternate&&a.base===8)c+=L;if(a.alternate&&a.base===16)c+=a.uppercase?"0X":dA;if(a.justify===aL&&a.filler===L)for(var
d=f;d<a.width;d++)c+=L;c+=b;if(a.justify===ay)for(var
d=f;d<a.width;d++)c+=ai;return an(c)}function
cq(a,b){function
j(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=Number.parseInt(a.toString().split(aL)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=new
Array(c+1).join(L);if(b>0)a=a+az+new
Array(b+1).join(L);return a}else
return a.toFixed(b)}}var
c,f=cF(a),e=f.prec<0?6:f.prec;if(b<0||b===0&&1/b===Number.NEGATIVE_INFINITY){f.sign=-1;b=-b}if(Number.isNaN(b)){c=b9;f.filler=ai}else if(!Number.isFinite(b)){c="inf";f.filler=ai}else
switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)===ca)c=c.slice(0,d-1)+L+c.slice(d-1);break;case"f":c=j(b,e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
i=c.indexOf(ca),h=+c.slice(i+1);if(h<-4||b>=1e21||b.toFixed(0).length>e){var
d=i-1;while(c.charAt(d)===L)d--;if(c.charAt(d)===az)d--;c=c.slice(0,d+1)+c.slice(i);d=c.length;if(c.charAt(d-3)===ca)c=c.slice(0,d-1)+L+c.slice(d-1);break}else{var
g=e;if(h<0){g-=h+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)===L)d--;if(c.charAt(d)===az)d--;c=c.slice(0,d+1)}}break}return cp(f,c)}function
bB(a,b){if(aP(a)===b5)return an(e+b);var
c=cF(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
d=b.toString(c.base);if(c.prec>=0){c.filler=ai;var
f=c.prec-d.length;if(f>0)d=aR(f,L)+d}return cp(c,d)}var
i3=0;function
a7(){return i3++}function
W(a){if(!z.Failure)z.Failure=[g,an(ck),-3];eY(z.Failure,a)}function
bE(a){if(cJ(a))return a;return e2(a)}function
bb(){return typeof
c.process!=="undefined"&&typeof
c.process.versions!=="undefined"&&typeof
c.process.versions.node!=="undefined"}function
jg(){function
a(a){if(a.charAt(0)===aj)return[e,a.slice(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||e,f=c.length>0&&c.charAt(1)!==":";if(b[2]||f){var
d=b[1]||e,g=b[2]||e;return[d,a.slice(d.length+g.length)]}return}return bb()&&c.process&&c.process.platform?c.process.platform===em?b:a:a}var
cK=jg();function
e0(a){return a.slice(-1)!==aj?a+aj:a}if(bb()&&c.process&&c.process.cwd)var
a6=c.process.cwd().replace(/\\/g,aj);else
var
a6="/static";a6=e0(a6);function
iW(a){a=bE(a);if(!cK(a))a=a6+a;var
e=cK(a),d=e[1].split(/[/\\]/),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
jb(a){for(var
g=e,c=g,b,i,d=0,h=a.length;d<h;d++){b=a.charCodeAt(d);if(b<Y){for(var
f=d+1;f<h&&(b=a.charCodeAt(f))<Y;f++);if(f-d>bn){c.slice(0,1);g+=c;c=e;g+=a.slice(d,f)}else
c+=a.slice(d,f);if(f===h)break;d=f}if(b<dK){c+=String.fromCharCode(0xc0|b>>6);c+=String.fromCharCode(Y|b&aM)}else if(b<0xd800||b>=dz)c+=String.fromCharCode(eh|b>>12,Y|b>>6&aM,Y|b&aM);else if(b>=0xdbff||d+1===h||(i=a.charCodeAt(d+1))<dl||i>dz)c+="\xef\xbf\xbd";else{d++;b=(b<<10)+i-0x35fdc00;c+=String.fromCharCode(dN|b>>18,Y|b>>12&aM,Y|b>>6&aM,Y|b&aM)}if(c.length>aZ){c.slice(0,1);g+=c;c=e}}return g+c}function
F(a){return cJ(a)?an(a):an(jb(a))}function
N(a){eW(z.Sys_error,F(a))}function
eX(a,b){throw h([0,a].concat(b))}var
jh=["E2BIG","EACCES","EAGAIN",aJ,"EBUSY","ECHILD","EDEADLK","EDOM",cj,"EFAULT","EFBIG","EINTR",aK,"EIO",b$,"EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",aY,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",bq,d7,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS",cf,"ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
e6(a,b,c,d){var
f=jh.indexOf(a);if(f<0){if(d==null)d=-9999;f=[0,-d]}var
g=[f,F(b||e),F(c||e)];return g}var
eS={};function
aQ(a){return eS[a]}function
f(a,b,c,d,e){var
f=aQ(el);if(a&&f)eX(f,e6(b,c,e));else{var
d=b+ei+d+b_+c;if(e!==undefined)d+=" '"+e+"'";N(d)}}function
cy(a){return a
instanceof
ac}function
cz(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
ij(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
ac(4,a,a.length)}function
eV(a,b){f(b,aY,bp,a)}function
e1(a){if(a.t!==4)by(a);return a.c}function
eB(a){return new
ac(4,a,a.length)}function
ae(a){return a.l}function
er(){}function
I(a){this.data=a}I.prototype=new
er();I.prototype.constructor=I;I.prototype.truncate=function(a){var
b=this.data;this.data=D(a|0);au(b,0,this.data,0,a)};I.prototype.length=function(){return ae(this.data)};I.prototype.write=function(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=D(a+d),g=this.data;this.data=f;au(g,0,this.data,0,e)}au(eB(b),c,this.data,a,d);return d};I.prototype.read=function(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d){var
f=D(d|0);au(this.data,a,f,0,d);b.set(e1(f),c)}return d};function
am(a,b,c){this.file=b;this.name=a;this.flags=c;this.offset=0;this.seeked=false}am.prototype.err_closed=function(a,b){f(b,aJ,a,a0)};am.prototype.length=function(){if(this.file)return this.file.length();this.err_closed("length")};am.prototype.truncate=function(a,b){if(this.file){if(!(this.flags.wronly||this.flags.rdwr))f(b,aK,d3,a1);return this.file.truncate(a)}this.err_closed(d3,b)};am.prototype.write=function(a,b,c,d){if(this.file&&(this.flags.wronly||this.flags.rdwr)){var
e=this.offset;this.offset+=c;return this.file.write(e,a,b,c)}this.err_closed(dU,d)};am.prototype.read=function(a,b,c,d){if(this.file&&!this.flags.wronly){var
e=this.offset;this.offset+=c;return this.file.read(e,a,b,c)}this.err_closed(dQ,d)};am.prototype.seek=function(a,b,c){switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)f(c,aK,bm,a1);this.offset=a;this.seeked=true};am.prototype.close=function(){if(!this.file)this.err_closed("close");this.file=undefined};am.prototype.check_stream_semantics=function(a){if(!this.file)return this.err_closed(a,1)};function
w(a,b){this.content={};this.root=a;this.lookupFun=b}w.prototype.nm=function(a){return this.root+a};w.prototype.create_dir_if_needed=function(a){var
d=a.split(aj),c=e;for(var
b=0;b<d.length-1;b++){c+=d[b]+aj;if(this.content[c])continue;this.content[c]=Symbol("directory")}};w.prototype.slash=function(a){return/\/$/.test(a)?a:a+aj};w.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(F(this.root),F(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
I(aA(b[1]))}}};w.prototype.exists=function(a,b){if(a===e)return 1;var
c=this.slash(a);if(this.content[c])return 1;if(!b)this.lookup(a);return this.content[a]?1:0};w.prototype.isFile=function(a){return this.exists(a)&&!this.is_dir(a)?1:0};w.prototype.mkdir=function(a,b,c){if(this.exists(a))f(c,cj,cg,dy,this.nm(a));var
d=/^(.*)\/[^/]+/.exec(a);d=d&&d[1]||e;if(!this.exists(d))f(c,aY,cg,bp,this.nm(a));if(!this.is_dir(d))f(c,bq,cg,dY,this.nm(a));this.create_dir_if_needed(this.slash(a))};w.prototype.rmdir=function(a,b){var
c=a===e?e:this.slash(a),g=new
RegExp(dV+c+dE);if(!this.exists(a))f(b,aY,b8,bp,this.nm(a));if(!this.is_dir(a))f(b,bq,b8,dY,this.nm(a));for(var
d
in
this.content)if(d.match(g))f(b,d7,b8,"directory not empty",this.nm(a));delete
this.content[c]};w.prototype.readdir=function(a){var
g=a===e?e:this.slash(a);if(!this.exists(a))N(a+": No such file or directory");if(!this.is_dir(a))N(a+": Not a directory");var
h=new
RegExp(dV+g+dE),d={},c=[];for(var
f
in
this.content){var
b=f.match(h);if(b&&!d[b[1]]){d[b[1]]=true;c.push(b[1])}}return c};w.prototype.opendir=function(a,b){var
c=this.readdir(a),d=false,e=0;return{readSync:function(){if(d)f(b,aJ,dM,a0);if(e===c.length)return null;var
a=c[e];e++;return{name:a}},closeSync:function(){if(d)f(b,aJ,dM,a0);d=true;c=[]}}};w.prototype.is_dir=function(a){if(a===e)return true;var
b=this.slash(a);return this.content[b]?1:0};w.prototype.unlink=function(a,b){if(!this.exists(a,true))f(b,aY,"unlink",bp,a);delete
this.content[a];return 0};w.prototype.open=function(a,b,c,d){var
e;this.lookup(a);if(this.content[a]){if(this.is_dir(a))f(d,b$,cc,eo,this.nm(a));if(b.create&&b.excl)f(d,cj,cc,dy,this.nm(a));e=this.content[a];if(b.truncate)e.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
I(D(0));e=this.content[a]}else
eV(this.nm(a),d);return new
am(this.nm(a),e,b)};w.prototype.truncate=function(a,b,c){var
d;this.lookup(a);if(this.content[a]){if(this.is_dir(a))f(c,b$,cc,eo,this.nm(a));d=this.content[a];d.truncate(b)}else
eV(this.nm(a),c)};w.prototype.register=function(a,b){var
c;if(this.content[a])N(this.nm(a)+" : file already exists");if(cy(b))c=new
I(b);if(cz(b))c=new
I(aA(b));else if(Array.isArray(b))c=new
I(ij(b));else if(typeof
b==="string")c=new
I(eA(b));else if(b.toString){var
d=aA(F(b.toString()));c=new
I(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
N(this.nm(a)+" : registering file with invalid content type")};w.prototype.constructor=w;function
u(a,b,c){var
d=aQ(el);if(b&&d){var
e=e6(a.code,c||a.syscall,a.path,a.errno);eX(d,e)}else
N(a.toString())}function
iG(a){if(a<0)a=Math.ceil(a);return new
d(a&U,Math.floor(a*a9)&U,Math.floor(a*a9*a9)&V)}function
cI(a,b){var
c;if(a.isFile())c=0;else if(a.isDirectory())c=1;else if(a.isCharacterDevice())c=2;else if(a.isBlockDevice())c=3;else if(a.isSymbolicLink())c=4;else if(a.isFIFO())c=5;else if(a.isSocket())c=6;return[0,a.dev,a.ino|0,c,a.mode,a.nlink,a.uid,a.gid,a.rdev,b?iG(a.size):a.size|0,a.atimeMs/ak,a.mtimeMs/ak,a.ctimeMs/ak]}function
A(a){return a.length}function
ao(a,b){return a.charCodeAt(b)}function
jl(a){var
d=A(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=ao(a,b);return c}function
M(a,b){this.fs=require(cl);this.fd=a;this.flags=b;var
c=this.fs.fstatSync(a);b.noSeek=c.isCharacterDevice()||c.isFIFO()||c.isSocket();this.offset=this.flags.append?c.size:0;this.seeked=false}M.prototype=new
er();M.prototype.constructor=M;M.prototype.truncate=function(a,b){try{this.fs.ftruncateSync(this.fd,a|0);if(this.offset>a)this.offset=a}catch(f){u(f,b)}};M.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(f){N(f.toString())}};M.prototype.write=function(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.writeSync(this.fd,a,b,c);else
var
e=this.fs.writeSync(this.fd,a,b,c,this.offset);this.offset+=e}catch(f){u(f,d)}return e};M.prototype.read=function(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.readSync(this.fd,a,b,c);else
var
e=this.fs.readSync(this.fd,a,b,c,this.offset);this.offset+=e;return e}catch(f){u(f,d)}};M.prototype.seek=function(a,b,c){if(this.flags.noSeek)f(c,cf,bm,dD);switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)f(c,aK,bm,a1);this.offset=a;this.seeked=true;return this.offset};M.prototype.stat=function(a){try{var
b=this.fs.fstatSync(this.fd);return cI(b,a)}catch(f){u(f,1)}};M.prototype.close=function(a){try{this.fs.closeSync(this.fd);return 0}catch(f){u(f,a)}};M.prototype.check_stream_semantics=function(a){try{var
b=this.fs.fstatSync(this.fd)}catch(f){u(f,1,a)}if(!(b.isFile()||b.isCharacterDevice()||b.isFIFO()||b.isSocket()))f(1,aK,a,a1)};function
b(a){this.fs=require(cl);this.root=a}b.prototype.nm=function(a){return this.root+a};b.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}};b.prototype.isFile=function(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){N(f.toString())}};b.prototype.mkdir=function(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){u(f,c)}};b.prototype.rmdir=function(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){u(f,b)}};b.prototype.readdir=function(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){u(f,b)}};b.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){N(f.toString())}};b.prototype.unlink=function(a,b){try{this.fs.unlinkSync(this.nm(a));return 0}catch(f){u(f,b)}};b.prototype.utimes=function(a,b,c,d){try{if(b===0&&c===0){b=new
Date().getTime()/ak;c=b}this.fs.utimesSync(this.nm(a),b,c);return 0}catch(f){u(f,d)}};b.prototype.truncate=function(a,b,c){try{this.fs.truncateSync(this.nm(a),b|0);return 0}catch(f){u(f,c)}};b.prototype.open=function(a,b,c,d){var
f=require("node:constants"),e=0;for(var
h
in
b)switch(h){case"rdonly":e|=f.O_RDONLY;break;case"wronly":e|=f.O_WRONLY;break;case"rdwr":e|=f.O_RDWR;break;case"append":e|=f.O_APPEND;break;case"create":e|=f.O_CREAT;break;case"truncate":e|=f.O_TRUNC;break;case"excl":e|=f.O_EXCL;break;case"binary":e|=f.O_BINARY;break;case"text":e|=f.O_TEXT;break;case"nonblock":e|=f.O_NONBLOCK;break;case"noctty":e|=f.O_NOCTTY;break;case"dsync":e|=f.O_DSYNC;break;case"sync":e|=f.O_SYNC;break}try{var
g=this.fs.openSync(this.nm(a),e,c);return new
M(g,b)}catch(f){u(f,d)}};if(c.process?.platform===em)b.prototype.rename=function(a,b,c){try{var
d=this.nm(b),e=this.nm(a),h,g;if((h=this.fs.statSync(d,{throwIfNoEntry:false}))&&(g=this.fs.statSync(e,{throwIfNoEntry:false}))&&g.isDirectory())if(h.isDirectory()){if(!d.startsWith(e))try{this.fs.rmdirSync(d)}catch{}}else{var
f=new
Error(`ENOTDIR: not a directory, rename '${e}' -> '${d}'`);throw Object.assign(f,{errno:-20,code:bq,syscall:"rename",path:d})}this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){u(f,c)}};else
b.prototype.rename=function(a,b,c){try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){u(f,c)}};b.prototype.stat=function(a,b,c){try{var
d=this.fs.statSync(this.nm(a));return cI(d,b)}catch(f){u(f,c)}};b.prototype.lstat=function(a,b,c){try{var
d=this.fs.lstatSync(this.nm(a));return cI(d,b)}catch(f){u(f,c)}};b.prototype.symlink=function(a,b,c,d){try{this.fs.symlinkSync(b,this.nm(c),a===0?null:a[1]?dC:"file");return 0}catch(f){u(f,d)}};b.prototype.readlink=function(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return F(c)}catch(f){u(f,b)}};b.prototype.opendir=function(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){u(f,b)}};b.prototype.constructor=b;function
eH(a){var
b=cK(a);if(!b)return;return b[0]+aj}var
bJ=eH(a6)||W("unable to compute caml_root"),aT=[];if(bb())aT.push({path:bJ,device:new
b(bJ)});else
aT.push({path:bJ,device:new
w(bJ)});aT.push({path:ea,device:new
w(ea)});function
e7(a){var
h=iW(a),a=h.join(aj),g=e0(a),d;for(var
f=0;f<aT.length;f++){var
c=aT[f];if(g.search(c.path)===0&&(!d||d.path.length<c.path.length))d={path:c.path,device:c.device,rest:a.slice(c.path.length,a.length)}}if(!d&&bb()){var
e=eH(a);if(e&&e.match(/^[a-zA-Z]:\/$/)){var
c={path:e,device:new
b(e)};aT.push(c);d={path:c.path,device:c.device,rest:a.slice(c.path.length,a.length)}}}if(d)return d;N("no device found for "+g)}function
io(a,b){var
c=e7(a);if(!c.device.register)W("cannot register file");c.device.register(c.rest,b);return 0}function
e3(a,b){var
a=F(a),b=an(b);return io(a,b)}function
iu(){var
b=c.jsoo_fs_tmp;if(b)for(var
a=0;a<b.length;a++)e3(b[a].name,b[a].content);c.jsoo_create_file=e3;c.jsoo_fs_tmp=[];return 0}function
cr(){return[0]}function
ix(a,b,c){if(!Number.isFinite(a)){if(Number.isNaN(a))return F(b9);return F(a>0?dP:"-infinity")}var
k=a===0&&1/a===Number.NEGATIVE_INFINITY?1:a>=0?0:1;if(k)a=-a;var
f=0;if(a===0);else if(a<1)while(a<1&&f>-1022){a*=2;f--}else
while(a>=2){a/=2;f++}var
l=f<0?e:aL,g=e;if(k)g=ay;else
switch(c){case
43:g=aL;break;case
32:g=ai;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(az);if(j<0)d+=az+aR(b,L);else{var
h=j+1+b;if(d.length<h)d+=aR(h-d.length,L);else
d=d.slice(0,h)}}return F(g+dA+d+"p"+l+f.toString(10))}function
R(a,b,c){return new
d(a,b,c)}function
iE(a){return+a.isZero()}function
bD(a){return new
d(a&U,a>>24&U,a>>31&V)}function
iJ(a){return a.toInt()}function
iD(a){return+a.isNeg()}function
eL(a){return a.neg()}function
iB(a,b){var
c=cF(a);if(c.signedconv&&iD(b)){c.sign=-1;b=eL(b)}var
d=e,i=bD(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(iJ(g.modulus))+d}while(!iE(b));if(c.prec>=0){c.filler=ai;var
f=c.prec-d.length;if(f>0)d=aR(f,L)+d}return cp(c,d)}function
eN(a,b){return a.or(b)}function
iP(a,b,c){return a.apply(b,cA(c))}function
eO(a){return!!a}function
iR(){var
b=console,c=["log","debug","info","warn",dq,"assert",dC,"dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
d(){}for(var
a=0;a<c.length;a++)if(!b[c[a]])b[c[a]]=d;return b}function
iS(a){var
d=a.length,c=new
Array(d+1);c[0]=0;for(var
b=0;b<d;b++)c[b+1]=a[b];return c}var
aO=aC;function
cB(c){return function(...a){if(a.length===0)a=[undefined];var
b=aO(c,a);return b
instanceof
Function?cB(b):b}}function
iQ(a){return a.l>=0?a.l:a.l=a.length}function
iT(b){return function(...a){var
c=iQ(b);a.length=c;return aO(b,a)}}function
cC(c){return function(...a){a.unshift(this);var
b=aO(c,a);return b
instanceof
Function?cB(b):b}}function
eJ(a,b){return a.add(b)}function
eK(a,b){return a.mul(b)}function
cx(a,b){return a.ucompare(b)<0}function
i4(a){var
b=0,f=A(a),d=10,e=1,c=1;if(f>0)switch(ao(a,b)){case
45:b++;e=-1;break;case
43:b++;e=1;break}if(b+1<f&&ao(a,b)===48)switch(ao(a,b+1)){case
120:case
88:c=0;d=16;b+=2;break;case
111:case
79:c=0;d=8;b+=2;break;case
98:case
66:c=0;d=2;b+=2;break;case
117:case
85:c=0;b+=2;break}return[b,e,d,c]}function
eU(a){if(a>=48&&a<=57)return a-48;if(a>=65&&a<=90)return a-55;if(a>=97&&a<=122)return a-87;return-1}function
eM(a){var
g=i4(a),f=g[0],j=g[1],h=g[2],k=g[3],i=bD(h),l=new
d(U,0xfffffff,V).udivmod(i).quotient,e=ao(a,f),b=eU(e);if(b<0||b>=h)W(a2);var
c=bD(b);for(;;){f++;e=ao(a,f);if(e===95)continue;b=eU(e);if(b<0||b>=h)break;if(cx(l,c))W(a2);b=bD(b);c=eJ(eK(i,c),b);if(cx(c,b))W(a2)}if(f!==A(a))W(a2);if(k&&cx(new
d(0,0,H),c))W(a2);if(j<0)c=eL(c);return c}var
iV=eM(F("0xdaba0b6eb09322e3")),iU=eM(F("0xd1342543de82ef95"));function
ie(a,b){return a.get(a.offset(b))}function
iL(a,b){return a.xor(b)}function
iI(a,b){return a.shift_right_unsigned(b)}function
iH(a,b){return a.shift_left(b)}function
bF(a){function
o(a,b){return iH(a,b)}function
h(a,b){return iI(a,b)}function
s(a,b){return eN(a,b)}function
f(a,b){return iL(a,b)}function
k(a,b){return eJ(a,b)}function
i(a,b){return eK(a,b)}function
m(a,b){return s(o(a,b),h(a,64-b))}function
g(a,b){return ie(a,b)}function
j(a,b,c){return a4(a,b,c)}var
q=iU,l=iV,b,d,c,e=a,r=g(e,0),n=g(e,1),p=g(e,2),t=g(e,3);b=k(n,p);b=i(f(b,h(b,32)),l);b=i(f(b,h(b,32)),l);b=f(b,h(b,32));j(e,1,k(i(n,q),r));var
d=p,c=t;c=f(c,d);d=m(d,24);d=f(f(d,c),o(c,16));c=m(c,37);j(e,2,d);j(e,3,c);return b}function
iX(){return 0}function
eq(a){this.id=a}function
a$(){this.map=new
c.WeakMap();this.opened=new
c.Set()}a$.prototype.close=function(a){this.opened.delete(a)};a$.prototype.get=function(a){return this.map.get(a)};a$.prototype.set=function(a,b){if(b.opened)this.opened.add(a);return this.map.set(a,b)};a$.prototype.all=function(){return this.opened.values()};var
bG=new
a$();function
cD(a){return bG.get(a)}function
af(a){var
b=cD(a);if(!b.opened)N("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr===0)return 0;if(b.output)b.output(bK(b.buffer,0,b.buffer_curr));else
for(var
c=0;c<b.buffer_curr;)c+=b.file.write(b.buffer,c,b.buffer_curr-c);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}function
i$(a,b){if(b.altname)try{var
d=require(cl),c=d.openSync(b.altname,"rs");return new
M(c,b)}catch(f){}return new
M(a,b)}var
aS=new
Array(3);function
as(a,b){I.call(this,D(0));this.log=function(a){return 0};if(a===1&&typeof
console.log==="function")this.log=console.log;else if(a===2&&typeof
console.error==="function")this.log=console.error;else if(typeof
console.log==="function")this.log=console.log;this.flags=b}as.prototype.length=function(){return 0};as.prototype.truncate=function(a,b){f(b,aK,"ftruncate",a1)};as.prototype.write=function(a,b,c,d){var
g=c;if(this.log){if(c>0&&b>=0&&b+c<=a.length&&a[b+c-1]===10)c--;var
e=D(c);au(eB(a),b,e,0,c);this.log(e.toUtf16());return g}f(d,aJ,dU,a0)};as.prototype.read=function(a,b,c,d){f(d,aJ,dQ,a0)};as.prototype.seek=function(a,b,c){f(c,cf,bm,dD)};as.prototype.close=function(){this.log=undefined};as.prototype.check_stream_semantics=function(a){};function
bL(a,b){var
c;if(b===undefined){b=aS.length;c=new
eq(b)}else if(aS[b])c=aS[b].chanid;else
c=new
eq(b);aS[b]={file:a,chanid:c};return b|0}function
jk(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;d.writeonly=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
e=e7(a),f=e.device.open(e.rest,d,c);return bL(f,undefined)}(function(){var
c=bb();function
a(a,b){return c?i$(a,b):new
as(a,b)}bL(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);bL(a(1,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),1);bL(a(2,{buffered:c?1:2,wronly:1,isCharacterDevice:true}),2)}());function
iY(a){var
b=aS[a];if(b===undefined)N(dO+a+d0);var
d=b.file,c=b.chanid,f=null,e={file:d,offset:d.offset,fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(dR),refill:f};bG.set(c,e);return c}function
eP(a){var
c=aS[a];if(c===undefined)N(dO+a+d0);var
b=c.file,d=c.chanid,e=b.flags.buffered!==undefined?b.flags.buffered:1,f={file:b,offset:b.offset,fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(dR),buffered:e};bG.set(d,f);return d}function
iZ(){var
a=0,d=bG.all();for(var
c
of
d){var
b=cD(c);if(b.opened&&b.out)a=[0,c,a]}return a}function
i1(a,b,c,d){var
e=cD(a);if(!e.opened)N("Cannot output to a closed channel");b=b.subarray(c,c+d);if(e.buffer_curr+b.length>e.buffer.length){var
g=new
Uint8Array(e.buffer_curr+b.length);g.set(e.buffer);e.buffer=g}switch(e.buffered){case
0:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;af(a);break;case
1:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)af(a);break;case
2:var
f=b.lastIndexOf(10);if(f<0){e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)af(a)}else{e.buffer.set(b.subarray(0,f+1),e.buffer_curr);e.buffer_curr+=f+1;af(a);e.buffer.set(b.subarray(f+1),e.buffer_curr);e.buffer_curr+=b.length-f-1}break}return 0}function
i0(a,b,c,d){var
b=e1(b);return i1(a,b,c,d)}function
eQ(a,b,c,d){return i0(a,aA(b),c,d)}function
cE(a,b){var
c=an(String.fromCharCode(b));eQ(a,c,0,1);return 0}function
iN(a){return a===245?1:0}var
jf=Math.log2&&Math.log2(1.1235582092889474e307)===1020;function
jd(a){if(jf)return Math.floor(Math.log2(a));var
b=0;if(a===0)return Number.NEGATIVE_INFINITY;if(a>=1)while(a>=2){a/=2;b++}else
while(a<1){a*=2;b--}return b}function
cs(a){var
b=new
Float32Array(1);b[0]=a;var
c=new
Int32Array(b.buffer);return c[0]|0}function
bC(a){if(!Number.isFinite(a)){if(Number.isNaN(a))return R(1,0,dX);return a>0?R(0,0,dX):R(0,0,0xfff0)}var
f=a===0&&1/a===Number.NEGATIVE_INFINITY?H:a>=0?0:H;if(f)a=-a;var
b=jd(a)+dT;if(b<=0){b=0;a/=Math.pow(2,-ds)}else{a/=Math.pow(2,b-d9);if(a<16){a*=2;b-=1}if(b===0)a/=2}var
d=Math.pow(2,24),c=a|0;a=(a-c)*d;var
e=a|0;a=(a-e)*d;var
g=a|0;c=c&cb|f|b<<4;return R(g,e,c)}function
a_(a){return a.toArray()}function
ez(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom===bs)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<V)a.write(16,b.dims[d]);else{a.write(16,V);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=a_(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=a_(bC(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
13:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
0:for(var
d=0;d<b.data.length;d++){var
f=cs(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,cs(e[1]));a.write(32,cs(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=a_(bC(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=a_(bC(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}function
ct(a){var
b=new
Int32Array(1);b[0]=a;var
c=new
Float32Array(b.buffer);return c[0]}function
a8(a){return new
d(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
cu(a){var
f=a.lo,g=a.mi,c=a.hi,d=(c&0x7fff)>>4;if(d===2047)return(f|g|c&cb)===0?c&H?Number.NEGATIVE_INFINITY:Number.POSITIVE_INFINITY:Number.NaN;var
e=Math.pow(2,-24),b=(f*e+g)*e+(c&cb);if(d>0){b+=16;b*=Math.pow(2,d-d9)}else
b*=Math.pow(2,-ds);if(c&H)b=-b;return b}function
ew(a,b,c){var
k=a.read32s();if(k<0||k>16)W("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&al,q=r>>8&1,j=[];if(c===bs)for(var
d=0;d<k;d++){var
p=a.read16u();if(p===V){var
u=a.read32u(),v=a.read32u();if(u!==0)W("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=bw(j),h=ev(l,f),i=cm(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)W("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=a8(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=cu(a8(g));i.set(d,m)}break;case
13:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
0:for(var
d=0;d<f;d++){var
m=ct(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=ct(a.read32s()),n=ct(a.read32s());i.set(d,[bo,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=cu(a8(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=cu(a8(g));i.set(d,[bo,o,n])}break}b[0]=(4+k)*4;return cm(l,q,j,h)}function
eu(a,b,c){return a.compare(b,c)}function
eR(a,b){return Math.imul(a,b)}function
ad(a,b){b=eR(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=eR(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
iv(a,b){if((b&bu)===bu&&(b&0x03ff)!==0)b=0x7c01;else if(b===H)b=0;return ad(a,b)}function
iw(a,b){a=ad(a,cw(b));a=ad(a,cv(b));return a}function
eI(a,b){return iw(a,bC(b))}function
ey(a){var
c=bw(a.dims),d=0;switch(a.kind){case
2:case
3:case
12:if(c>ci)c=ci;var
e=0,b=0;for(b=0;b+4<=a.data.length;b+=4){e=a.data[b+0]|a.data[b+1]<<8|a.data[b+2]<<16|a.data[b+3]<<24;d=ad(d,e)}e=0;switch(c&3){case
3:e=a.data[b+2]<<16;case
2:e|=a.data[b+1]<<8;case
1:e|=a.data[b+0];d=ad(d,e)}break;case
4:case
5:if(c>ar)c=ar;var
e=0,b=0;for(b=0;b+2<=a.data.length;b+=2){e=a.data[b+0]|a.data[b+1]<<16;d=ad(d,e)}if((c&1)!==0)d=ad(d,a.data[b]);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=ad(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=ad(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=ad(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=eI(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=eI(d,a.data[b]);break;case
13:if(c>ar)c=ar;for(var
b=0;b<c;b++)d=iv(d,a.data[b]);break}return d}function
iy(a,b){b[0]=4;return a.read32s()}function
i2(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:W("input_value: native integer value too large");break;default:W("input_value: ill-formed native integer")}}function
iK(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return a8(d)}function
iF(a,b,c){var
e=a_(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
iz(a,b,c){return a.compare(b)}function
iC(a){return a.lo32()^a.hi32()}var
eE={_j:{deserialize:iK,serialize:iF,fixed_length:8,compare:iz,hash:iC},_i:{deserialize:iy,fixed_length:4},_n:{deserialize:i2,fixed_length:4},_bigarray:{deserialize:function(a,b){return ew(a,b,"_bigarray")},serialize:ez,compare:eu,hash:ey},_bigarr02:{deserialize:function(a,b){return ew(a,b,bs)},serialize:ez,compare:eu,hash:ey}};function
co(a){return eE[a.caml_custom]&&eE[a.caml_custom].compare}function
eC(a,b,c,d){var
f=co(b);if(f){var
e=c>0?f(b,a,d):f(a,b,d);if(d&&Number.isNaN(e))return c;if(Number.isNaN(+e))return+e;if((e|0)!==0)return e|0}return c}function
eD(a){if(typeof
a==="number")return ak;else if(cy(a))return bl;else if(cz(a))return 1252;else if(Array.isArray(a)&&a[0]===a[0]>>>0&&a[0]<=dH){var
b=a[0]|0;return b===bo?0:b}else if(a
instanceof
String)return dp;else if(typeof
a==="string")return dp;else if(a
instanceof
Number)return ak;else if(a&&a.caml_custom)return ce;else if(a&&a.compare)return 1256;else if(typeof
a==="function")return 1247;else if(typeof
a==="symbol")return 1251;return 1001}function
iM(a,b){if(a<b)return-1;if(a===b)return 0;return 1}function
jj(a,b){return a<b?-1:a>b?1:0}function
ii(a,b){a.t&6&&bz(a);b.t&6&&bz(b);return a.c<b.c?-1:a.c>b.c?1:0}function
il(a,b,c){var
f=[];for(;;){if(!(c&&a===b)){var
e=eD(a);if(e===dn){a=a[1];continue}var
g=eD(b);if(g===dn){b=b[1];continue}if(e!==g){if(e===ak){if(g===ce)return eC(a,b,-1,c);return-1}if(g===ak){if(e===ce)return eC(b,a,1,c);return 1}return e<g?-1:1}switch(e){case
247:k(ch);break;case
248:var
d=iM(a[2],b[2])|0;if(d!==0)return d;break;case
249:k(ch);break;case
250:k("equal: got Forward_tag, should not happen");break;case
251:k("equal: abstract value");break;case
252:if(a!==b){var
d=ii(a,b)|0;if(d!==0)return d}break;case
253:k("equal: got Double_tag, should not happen");break;case
254:k("equal: got Double_array_tag, should not happen");break;case
255:k("equal: got Custom_tag, should not happen");break;case
1247:k(ch);break;case
1255:var
i=co(a);if(i!==co(b))return a.caml_custom<b.caml_custom?-1:1;if(!i)k("compare: abstract value");var
d=i(a,b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1256:var
d=a.compare(b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!==b){if(!c)return Number.NaN;if(!Number.isNaN(a))return 1;if(!Number.isNaN(b))return-1}break;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!==b)return c?1:Number.NaN;break;case
1251:if(a!==b)return c?1:Number.NaN;break;case
1252:var
a=aP(a),b=aP(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;default:if(iN(e)){k("compare: continuation value");break}if(a.length!==b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1);break}}if(f.length===0)return 0;var
h=f.pop();b=f.pop();a=f.pop();if(h+1<a.length)f.push(a,b,h+1);a=a[h];b=b[h]}}function
aD(a,b){return+(il(a,b,false)!==0)}function
bH(a){if(Array.isArray(a)&&a[0]===a[0]>>>0)return a[0];else if(cy(a))return bl;else if(cz(a))return bl;else if(a
instanceof
Function||typeof
a==="function")return 247;else if(a&&a.caml_custom)return dH;else
return ak}var
e5=undefined;function
ig(a){var
d={},c=-1;if(a)for(var
b=1;b<a.length;b++){var
e=a[b][2];c=Math.max(c,e);d[bE(a[b][1])]=e}d.next_idx=c+1;return d}function
X(a,b,c){if(c){var
d=c;if(e5)a=aO(e5,[d]);else if(z.symbols){if(!z.symidx)z.symidx=ig(z.symbols);var
e=z.symidx[d];if(e>=0)a=e;else{var
a=z.symidx.next_idx++;z.symidx[d]=a}}}z[a+1]=b;if(c)z[c]=b}function
cG(a,b){eS[aP(a)]=b;return 0}function
i8(){k(b6)}function
O(a,b){if(b>>>0>=A(a))i8();return ao(a,b)}function
S(a){a.t&6&&bz(a);return an(a.c)}function
i9(){return ee/4|0}function
i_(a){if(c.quit)c.quit(a);if(c.process&&c.process.exit)c.process.exit(a);k("Function 'exit' not implemented")}function
ba(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
n(a,b,c){return{joo_tramp:a,joo_args:b,joo_direct:c}}function
ja(a,b){if(b.fun){a.fun=b.fun;return 0}if(typeof
b==="function"){a.fun=b;return 0}var
c=b.length;while(c--)a[c]=b[c];return 0}function
aE(a){{if(Array.isArray(a))return a;var
b;if(c.RangeError&&a
instanceof
c.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=z.Stack_overflow;else if(c.InternalError&&a
instanceof
c.InternalError&&a.message&&a.message.match(/too much recursion/i))b=z.Stack_overflow;else if(a
instanceof
c.Error&&aQ(cd))b=[0,aQ(cd),a];else
b=[0,z.Failure,F(String(a))];if(a
instanceof
c.Error)b.js_error=a;return b}}function
iO(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}function
it(a){var
b=e;if(a[0]===0){b+=a[1][1];if(a.length===3&&a[2][0]===0&&iO(a[1]))var
f=a[2],h=1;else
var
h=2,f=a;b+="(";for(var
d=h;d<f.length;d++){if(d>h)b+=b_;var
c=f[d];if(typeof
c==="number")b+=c.toString();else if(c
instanceof
ac)b+=bk+c.toString()+bk;else if(typeof
c==="string")b+=bk+c.toString()+bk;else
b+=ec}b+=")"}else if(a[0]===g)b+=a[1];return b}function
eG(a){if(Array.isArray(a)&&(a[0]===0||a[0]===g)){var
c=aQ(ef);if(c)aO(c,[a,false]);else{var
d=it(a),b=aQ(dS);if(b)aO(b,[0]);console.error(br+d);if(a.js_error)throw a.js_error}}else
throw a}function
i7(){var
d=c.process;if(d&&d.on)d.on("uncaughtException",function(a,b){eG(a);d.exit(2)});else if(c.addEventListener)c.addEventListener(dq,function(a){if(a.error)eG(a.error)})}i7();function
i(a,b){return(a.l>=0?a.l:a.l=a.length)===1?a(b):aC(a,[b])}function
Q(a,b,c){return(a.l>=0?a.l:a.l=a.length)===2?a(b,c):aC(a,[b,c])}function
b4(a,b,c,d,e,f){return(a.l>=0?a.l:a.l=a.length)===5?a(b,c,d,e,f):aC(a,[b,c,d,e,f])}function
h$(a,b,c,d,e,f,g,h){return(a.l>=0?a.l:a.l=a.length)===7?a(b,c,d,e,f,g,h):aC(a,[b,c,d,e,f,g,h])}var
ji=0;iu();var
bM=[g,en,-1],cP=[g,dL,-2],cM=[g,ck,-3],cL=[g,dv,-4],cN=[g,ej,-8],cO=[g,d6,-9],q=[g,d$,-11],cQ=[g,eg,-12],h_=[4,0,0,0,[12,45,[4,0,0,0,0]]],bR=[0,[11,'File "',[2,0,[11,'", line ',[4,0,0,0,[11,ek,[4,0,0,0,[12,45,[4,0,0,0,[11,ei,[2,0,0]]]]]]]]]],'File "%s", line %d, characters %d-%d: %s'],db="wakeup";X(11,cQ,eg);X(10,q,d$);X(9,[g,ed,-10],ed);X(8,cO,d6);X(7,cN,ej);X(6,[g,dx,-7],dx);X(5,[g,dJ,-6],dJ);X(4,[g,dW,-5],dW);X(3,cL,dv);X(2,cM,ck);X(1,cP,dL);X(0,bM,en);function
p(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,p(a[1])];case
1:return[1,p(a[1])];case
2:return[2,p(a[1])];case
3:return[3,p(a[1])];case
4:return[4,p(a[1])];case
5:return[5,p(a[1])];case
6:return[6,p(a[1])];case
7:return[7,p(a[1])];case
8:var
c=a[1];return[8,c,p(a[2])];case
9:var
b=a[1];return[9,b,b,p(a[3])];case
10:return[10,p(a[1])];case
11:return[11,p(a[1])];case
12:return[12,p(a[1])];case
13:return[13,p(a[1])];default:return[14,p(a[1])]}}function
E(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,E(a[1],b)];case
1:return[1,E(a[1],b)];case
2:return[2,E(a[1],b)];case
3:return[3,E(a[1],b)];case
4:return[4,E(a[1],b)];case
5:return[5,E(a[1],b)];case
6:return[6,E(a[1],b)];case
7:return[7,E(a[1],b)];case
8:var
c=a[1];return[8,c,E(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,E(a[3],b)];case
10:return[10,E(a[1],b)];case
11:return[11,E(a[1],b)];case
12:return[12,E(a[1],b)];case
13:return[13,E(a[1],b)];default:return[14,E(a[1],b)]}}function
o(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,o(a[1],b)];case
1:return[1,o(a[1],b)];case
2:var
c=a[1];return[2,c,o(a[2],b)];case
3:var
d=a[1];return[3,d,o(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,o(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,o(a[4],b)];case
6:var
k=a[3],l=a[2],m=a[1];return[6,m,l,k,o(a[4],b)];case
7:var
n=a[3],p=a[2],q=a[1];return[7,q,p,n,o(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,o(a[4],b)];case
9:var
u=a[1];return[9,u,o(a[2],b)];case
10:return[10,o(a[1],b)];case
11:var
v=a[1];return[11,v,o(a[2],b)];case
12:var
w=a[1];return[12,w,o(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,o(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,o(a[3],b)];case
15:return[15,o(a[1],b)];case
16:return[16,o(a[1],b)];case
17:var
B=a[1];return[17,B,o(a[2],b)];case
18:var
C=a[1];return[18,C,o(a[2],b)];case
19:return[19,o(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,o(a[3],b)];case
21:var
F=a[1];return[21,F,o(a[2],b)];case
22:return[22,o(a[1],b)];case
23:var
G=a[1];return[23,G,o(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,o(a[3],b)]}}var
e9="true",e_="false";function
Z(a){throw h([0,cL,a],1)}function
bc(a){return 0<=a?a:-a|0}iY(0);eP(1);var
B=eP(2);function
av(a,b){eQ(a,b,0,A(b))}function
cR(a){av(B,a);cE(B,10);return af(B)}var
cS=[0,function(a){}],e$=[0,function(a){var
b=iZ(0);for(;;){if(!b)return 0;var
d=b[2],e=b[1];try{af(e)}catch(f){var
c=aE(f);if(c[1]!==cP)throw h(c,0)}b=d}}];function
bd(a){i(cS[1],0);return i(bv(e$),0)}cG(dS,bd);var
aU=(4*i9(0)|0)-1|0,fh="String.sub / Bytes.sub",fi="Bytes.blit",fj="String.blit / Bytes.blit_string";function
aw(a,b){var
c=D(a);is(c,0,a,b);return c}function
cT(a,b,c){a:{if(0<=b&&0<=c&&(ae(a)-c|0)>=b){var
d=D(c);au(a,b,d,0,c);var
e=d;break a}var
e=Z(fh)}return S(e)}function
cU(a,b,c,d,e){if(0<=e&&0<=b&&(ae(a)-e|0)>=b&&0<=d&&(ae(c)-e|0)>=d){au(a,b,c,d,e);return}return Z(fi)}function
_(a,b,c,d,e){if(0<=e&&0<=b&&(A(a)-e|0)>=b&&0<=d&&(ae(c)-e|0)>=d){bx(a,b,c,d,e);return}return Z(fj)}function
cV(a,b){var
c=[0,a,0],d=b[3];if(d){b[1]=b[1]+1|0;d[2]=c;b[3]=c;return}b[1]=1;b[2]=c;b[3]=c}var
fm="Buffer.add: cannot grow buffer",fn="Buffer.add_substring";function
cW(a,b){var
d=a[2],c=[0,a[1][2]];for(;;){if(c[1]>=(d+b|0))break;c[1]=2*c[1]|0}if(aU<c[1]){if((d+b|0)>aU)throw h([0,cM,fm],1);c[1]=aU}var
e=D(c[1]);cU(a[1][1],0,e,0,a[2]);a[1]=[0,e,c[1]]}function
aV(a,b){var
c=A(b),i=c<0?1:0,j=0,g=i||((A(b)-c|0)<0?1:0);if(g)Z(fn);var
d=a[2],e=a[1],f=d+c|0,h=e[1];if(e[2]<f){cW(a,c);_(b,j,a[1][1],a[2],c)}else
bx(b,0,h,d,c);a[2]=f}var
be=[0,0];iq(es(8,be));var
dk=[0,0],fa=[0,0];function
cX(a,b){var
d=[0,ib(fa,1),b];if(a){var
e=[0,d,a[1]];for(;;){var
c=bv(dk);if(!(1-et(dk,c,[0,e,c])))break}}return d}var
cY=cX(0,function(a){return function(a){return 0}}),fk="Array.blit",fo=[0,"domain.ml",184,13];cS[1]=function(a){var
b=cY[1];a:{b:{var
o=cY[2];for(;;){var
d=eF(0),c=d.length-1;if(b<c)break b;var
e=c;for(;;){if(b<e)break;e=2*e|0}var
f=es(e,be);c:{if(0<=c&&(d.length-1-c|0)>=0&&(f.length-1-c|0)>=0){ia(d,0,f,0,c);break c}Z(fk)}if(ip(d,f))break}var
l=f;break a}var
l=d}var
g=a5(l,b)[1+b];if(g!==be)var
k=g;else{var
m=i(o,0),j=eF(0),p=a5(j,b)[1+b]===g?(j[1+b]=m,1):0;if(p)var
k=m;else{var
n=a5(j,b)[1+b];if(n===be)throw h([0,q,fo],1);var
k=n}}return i(k,0)};var
fp="@]",fq="@}",fr="@?",fs="@\n",ft="@.",fu="@@",fv="@%",fw="%c",fx="%s",fy=dB,fz=dr,fA=ep,fB=dw,fC="%f",fD="%B",fE="%{",fF="%}",fG="%(",fH="%)",fI="%a",fJ="%t",fK="%?",fL="%r",fM="%_r",fN=[0,a,850,23],fO=[0,a,837,26],fP=[0,a,847,28],fQ=[0,a,815,21],fR=[0,a,819,21],fS=[0,a,823,19],fT=[0,a,827,22],fU=[0,a,832,30],fV=[0,a,851,23],fW=[0,a,836,26],fX=[0,a,846,28],fY=[0,a,814,21],fZ=[0,a,818,21],f0=[0,a,822,19],f1=[0,a,826,22],f2=[0,a,831,30];function
bN(a){return 5===a[2]?12:-6}function
cZ(a){return[0,0,D(a)]}function
c0(a,b){var
c=ae(a[2]),d=a[1]+b|0;if(c<d){var
e=c*2|0,g=d<=e?e:d,f=D(g);cU(a[2],0,f,0,c);a[2]=f}}function
aF(a,b){c0(a,1);aB(a[2],a[1],b);a[1]=a[1]+1|0}function
x(a,b){var
c=A(b);c0(a,c);_(b,0,a[2],a[1],c);a[1]=a[1]+c|0}function
c1(a){return cT(a[2],0,a[1])}function
c2(a){if(typeof
a==="number")switch(a){case
0:return fp;case
1:return fq;case
2:return fr;case
3:return fs;case
4:return ft;case
5:return fu;default:return fv}switch(a[0]){case
0:return a[1];case
1:return a[1];default:return"@"+S(aw(1,a[1]))}}function
bO(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
d=c[1];x(a,fw);c=d;break;case
1:var
e=c[1];x(a,fx);c=e;break;case
2:var
f=c[1];x(a,fy);c=f;break;case
3:var
g=c[1];x(a,fz);c=g;break;case
4:var
h=c[1];x(a,fA);c=h;break;case
5:var
i=c[1];x(a,fB);c=i;break;case
6:var
j=c[1];x(a,fC);c=j;break;case
7:var
k=c[1];x(a,fD);c=k;break;case
8:var
l=c[2],m=c[1];x(a,fE);bO(a,m);x(a,fF);c=l;break;case
9:var
n=c[3],o=c[1];x(a,fG);bO(a,o);x(a,fH);c=n;break;case
10:var
p=c[1];x(a,fI);c=p;break;case
11:var
q=c[1];x(a,fJ);c=q;break;case
12:var
r=c[1];x(a,fK);c=r;break;case
13:var
s=c[1];x(a,fL);c=s;break;default:var
t=c[1];x(a,fM);c=t}}}function
s(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,s(a[1])];case
1:return[1,s(a[1])];case
2:return[2,s(a[1])];case
3:return[3,s(a[1])];case
4:return[4,s(a[1])];case
5:return[5,s(a[1])];case
6:return[6,s(a[1])];case
7:return[7,s(a[1])];case
8:var
b=a[1];return[8,b,s(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,s(a[3])];case
10:return[10,s(a[1])];case
11:return[11,s(a[1])];case
12:return[12,s(a[1])];case
13:return[13,s(a[1])];default:return[14,s(a[1])]}}function
y(a){if(typeof
a==="number")return[0,,function(a){},,function(a){}];switch(a[0]){case
0:var
b=y(a[1]),r=b[2];return[0,,function(a){r(0)},,b[4]];case
1:var
c=y(a[1]),u=c[2];return[0,,function(a){u(0)},,c[4]];case
2:var
d=y(a[1]),v=d[2];return[0,,function(a){v(0)},,d[4]];case
3:var
e=y(a[1]),w=e[2];return[0,,function(a){w(0)},,e[4]];case
4:var
f=y(a[1]),x=f[2];return[0,,function(a){x(0)},,f[4]];case
5:var
g=y(a[1]),z=g[2];return[0,,function(a){z(0)},,g[4]];case
6:var
h=y(a[1]),A=h[2];return[0,,function(a){A(0)},,h[4]];case
7:var
i=y(a[1]),B=i[2];return[0,,function(a){B(0)},,i[4]];case
8:var
j=y(a[2]),C=j[2];return[0,,function(a){C(0)},,j[4]];case
9:var
D=a[2],E=a[1],k=y(a[3]),F=k[4],G=k[2],l=y(t(s(E),D)),H=l[4],I=l[2];return[0,,function(a){I(0);G(0)},,function(a){H(0);F(0)}];case
10:var
m=y(a[1]),J=m[2];return[0,,function(a){J(0)},,m[4]];case
11:var
n=y(a[1]),K=n[2];return[0,,function(a){K(0)},,n[4]];case
12:var
o=y(a[1]),L=o[2];return[0,,function(a){L(0)},,o[4]];case
13:var
p=y(a[1]),M=p[4],N=p[2];return[0,,function(a){N(0)},,function(a){M(0)}];default:var
q=y(a[1]),O=q[4],P=q[2];return[0,,function(a){P(0)},,function(a){O(0)}]}}function
t(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:var
d=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,t(d,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
1:var
e=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,t(e,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
2:var
f=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,t(f,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
3:var
g=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,t(g,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
4:var
i=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,t(i,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
5:var
j=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,t(j,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
6:var
k=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,t(k,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
7:var
l=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,t(l,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
8:var
m=a[2],n=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
o=b[1],p=t(m,b[2]);return[8,t(n,o),p];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw h([0,q,fW],1);case
9:var
r=a[3],u=a[2],v=a[1];if(typeof
b!=="number")switch(b[0]){case
8:break f;case
9:var
w=b[3],x=b[2],z=b[1],c=y(t(s(u),z)),A=c[4];c[2].call(null,0);A(0);return[9,v,x,t(r,w)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw h([0,q,fX],1);case
10:var
B=a[1];if(typeof
b!=="number"&&10===b[0])return[10,t(B,b[1])];throw h([0,q,fY],1);case
11:var
C=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:return[11,t(C,b[1])]}throw h([0,q,fZ],1);case
12:var
D=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:return[12,t(D,b[1])]}throw h([0,q,f0],1);case
13:var
E=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:return[13,t(E,b[1])]}throw h([0,q,f1],1);default:var
F=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:return[14,t(F,b[1])]}throw h([0,q,f2],1)}throw h([0,q,fV],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw h([0,q,fN],1)}}throw h([0,q,fP],1)}throw h([0,q,fO],1)}throw h([0,q,fU],1)}throw h([0,q,fT],1)}throw h([0,q,fS],1)}throw h([0,q,fR],1)}throw h([0,q,fQ],1)}var
v=[g,"CamlinternalFormat.Type_mismatch",a7(0)];function
e8(a){return a?e9:e_}var
fb="\\\\",fc="\\'",fd="\\b",fe="\\t",ff="\\n",fg="\\r",f4=b5,f5="%+d",f6="% d",f7=dB,f8="%+i",f9="% i",f_="%x",f$="%#x",ga="%X",gb="%#X",gc="%o",gd="%#o",ge=dZ,gf="%Ld",gg="%+Ld",gh="% Ld",gi=dw,gj="%+Li",gk="% Li",gl="%Lx",gm="%#Lx",gn="%LX",go="%#LX",gp="%Lo",gq="%#Lo",gr="%Lu",gs="%ld",gt="%+ld",gu="% ld",gv=dr,gw="%+li",gx="% li",gy="%lx",gz="%#lx",gA="%lX",gB="%#lX",gC="%lo",gD="%#lo",gE="%lu",gF="%nd",gG="%+nd",gH="% nd",gI=ep,gJ="%+ni",gK="% ni",gL="%nx",gM="%#nx",gN="%nX",gO="%#nX",gP="%no",gQ="%#no",gR="%nu",gS=[0,dm],gX="neg_infinity",gY=dP,gZ=b9,g1=[0,a,1558,4],g2="Printf: bad conversion %[",g3=[0,a,1626,39],g4=[0,a,1649,31],g5=[0,a,1650,31],g6="Printf: bad conversion %_",g7=dI,g8=eb,g9=dI,g_=eb;function
bf(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw h(v,1)}function
aW(a,b,c){var
d=bf(a,c);if(typeof
b!=="number")return[0,d[1],[0,b[1]],d[2]];if(!b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw h(v,1)}function
m(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){var
w=m(a[1],b[1]);return[0,[0,w[1]],w[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){var
x=m(a[1],b[1]);return[0,[1,x[1]],x[2]]}break;case
2:var
ag=a[2],y=bf(a[1],b),e=y[2],ah=y[1];if(typeof
e!=="number"&&1===e[0]){var
z=m(ag,e[1]);return[0,[2,ah,z[1]],z[2]]}throw h(v,1);case
3:var
ai=a[2],A=bf(a[1],b),f=A[2],aj=A[1];if(typeof
f!=="number"&&1===f[0]){var
B=m(ai,f[1]);return[0,[3,aj,B[1]],B[2]]}throw h(v,1);case
4:var
ak=a[4],al=a[1],g=aW(a[2],a[3],b),i=g[3],am=g[1];if(typeof
i!=="number"&&2===i[0]){var
an=g[2],C=m(ak,i[1]);return[0,[4,al,am,an,C[1]],C[2]]}throw h(v,1);case
5:var
ao=a[4],ap=a[1],j=aW(a[2],a[3],b),k=j[3],aq=j[1];if(typeof
k!=="number"&&3===k[0]){var
ar=j[2],D=m(ao,k[1]);return[0,[5,ap,aq,ar,D[1]],D[2]]}throw h(v,1);case
6:var
as=a[4],at=a[1],l=aW(a[2],a[3],b),n=l[3],au=l[1];if(typeof
n!=="number"&&4===n[0]){var
av=l[2],E=m(as,n[1]);return[0,[6,at,au,av,E[1]],E[2]]}throw h(v,1);case
7:var
aw=a[4],ax=a[1],o=aW(a[2],a[3],b),q=o[3],ay=o[1];if(typeof
q!=="number"&&5===q[0]){var
az=o[2],F=m(aw,q[1]);return[0,[7,ax,ay,az,F[1]],F[2]]}throw h(v,1);case
8:var
aA=a[4],aB=a[1],r=aW(a[2],a[3],b),s=r[3],aC=r[1];if(typeof
s!=="number"&&6===s[0]){var
aE=r[2],H=m(aA,s[1]);return[0,[8,aB,aC,aE,H[1]],H[2]]}throw h(v,1);case
9:var
aF=a[2],I=bf(a[1],b),t=I[2],aG=I[1];if(typeof
t!=="number"&&7===t[0]){var
K=m(aF,t[1]);return[0,[9,aG,K[1]],K[2]]}throw h(v,1);case
10:var
L=m(a[1],b);return[0,[10,L[1]],L[2]];case
11:var
aH=a[1],M=m(a[2],b);return[0,[11,aH,M[1]],M[2]];case
12:var
aI=a[1],N=m(a[2],b);return[0,[12,aI,N[1]],N[2]];case
13:if(typeof
b!=="number"&&8===b[0]){var
O=b[1],aJ=b[2],aK=a[3],aL=a[1];if(aD([0,a[2]],[0,O]))throw h(v,1);var
P=m(aK,aJ);return[0,[13,aL,O,P[1]],P[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){var
Q=b[1],aM=b[3],aN=a[3],aO=a[2],aP=a[1],aQ=[0,p(Q)];if(aD([0,p(aO)],aQ))throw h(v,1);var
R=m(aN,p(aM));return[0,[14,aP,Q,R[1]],R[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){var
S=m(a[1],b[1]);return[0,[15,S[1]],S[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){var
T=m(a[1],b[1]);return[0,[16,T[1]],T[2]]}break;case
17:var
aR=a[1],U=m(a[2],b);return[0,[17,aR,U[1]],U[2]];case
18:var
V=a[2],u=a[1];if(0===u[0]){var
Z=u[1],aV=Z[2],_=m(Z[1],b),aX=_[1],$=m(V,_[2]);return[0,[18,[0,[0,aX,aV]],$[1]],$[2]]}var
aa=u[1],aY=aa[2],ab=m(aa[1],b),aZ=ab[1],ac=m(V,ab[2]);return[0,[18,[1,[0,aZ,aY]],ac[1]],ac[2]];case
19:if(typeof
b!=="number"&&13===b[0]){var
W=m(a[1],b[1]);return[0,[19,W[1]],W[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){var
aS=a[2],aT=a[1],X=m(a[3],b[1]);return[0,[20,aT,aS,X[1]],X[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){var
aU=a[1],Y=m(a[2],b[1]);return[0,[21,aU,Y[1]],Y[2]]}break;case
23:var
d=a[2],c=a[1];if(typeof
c!=="number")switch(c[0]){case
0:return J(c,d,b);case
1:return J(c,d,b);case
2:return J(c,d,b);case
3:return J(c,d,b);case
4:return J(c,d,b);case
5:return J(c,d,b);case
6:return J(c,d,b);case
7:return J(c,d,b);case
8:return J([8,c[1],c[2]],d,b);case
9:var
a0=c[1],ae=G(c[2],d,b),af=ae[2];return[0,[23,[9,a0,ae[1]],af[1]],af[2]];case
10:return J(c,d,b);default:return J(c,d,b)}switch(c){case
0:return J(c,d,b);case
1:return J(c,d,b);case
2:if(typeof
b!=="number"&&14===b[0]){var
ad=m(d,b[1]);return[0,[23,2,ad[1]],ad[2]]}throw h(v,1);default:return J(c,d,b)}}throw h(v,1)}function
J(a,b,c){var
d=m(b,c);return[0,[23,a,d[1]],d[2]]}function
G(a,b,c){if(typeof
a==="number")return[0,0,m(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=G(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
g=G(a[1],b,c[1]);return[0,[1,g[1]],g[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
i=G(a[1],b,c[1]);return[0,[2,i[1]],i[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
j=G(a[1],b,c[1]);return[0,[3,j[1]],j[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
k=G(a[1],b,c[1]);return[0,[4,k[1]],k[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
l=G(a[1],b,c[1]);return[0,[5,l[1]],l[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
n=G(a[1],b,c[1]);return[0,[6,n[1]],n[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
o=G(a[1],b,c[1]);return[0,[7,o[1]],o[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
q=c[1],C=c[2],D=a[2];if(aD([0,a[1]],[0,q]))throw h(v,1);var
r=G(D,b,C);return[0,[8,q,r[1]],r[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],E=c[3],F=a[3],H=a[2],I=a[1],J=[0,p(e)];if(aD([0,p(I)],J))throw h(v,1);var
K=[0,p(d)];if(aD([0,p(H)],K))throw h(v,1);var
u=y(t(s(e),d)),L=u[4];u[2].call(null,0);L(0);var
w=G(p(F),b,E),M=w[2];return[0,[9,e,d,s(w[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
x=G(a[1],b,c[1]);return[0,[10,x[1]],x[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
z=G(a[1],b,c[1]);return[0,[11,z[1]],z[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
A=G(a[1],b,c[1]);return[0,[13,A[1]],A[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
B=G(a[1],b,c[1]);return[0,[14,B[1]],B[2]]}break}throw h(v,1)}function
K(a,b,c){var
d=A(c),g=0<=b?a:0,f=bc(b);if(f<=d)return c;var
h=2===g?48:32,e=aw(f,h);switch(g){case
0:_(c,0,e,0,d);break;case
1:_(c,0,e,f-d|0,d);break;default:a:if(0<d){if(43!==O(c,0)&&45!==O(c,0)&&32!==O(c,0))break a;aB(e,0,O(c,0));_(c,1,e,(f-d|0)+1|0,d-1|0);break}a:if(1<d&&48===O(c,0)){if(d_!==O(c,1)&&88!==O(c,1))break a;aB(e,1,O(c,1));_(c,2,e,(f-d|0)+2|0,d-2|0);break}_(c,0,e,f-d|0,d)}return S(e)}function
aG(a,b){var
d=bc(a),c=A(b),e=O(b,0);a:{b:{if(58>e){if(32!==e){if(43>e)break a;switch(e-43|0){case
5:c:if(c<(d+2|0)&&1<c){if(d_!==O(b,1)&&88!==O(b,1))break c;var
g=aw(d+2|0,48);aB(g,1,O(b,1));_(b,2,g,(d-c|0)+4|0,c-2|0);return S(g)}break b;case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(c>=(d+1|0))break a;var
f=aw(d+1|0,48);aB(f,0,e);_(b,1,f,(d-c|0)+2|0,c-1|0);return S(f)}if(71<=e){if(5<e+dF>>>0)break a}else if(65>e)break a}if(c<d){var
h=aw(d,48);_(b,0,h,d-c|0,c);return S(h)}}return b}function
f3(a){var
e=aA(a),b=[0,0],l=ae(e)-1|0,q=0;if(l>=0){var
h=q;for(;;){var
f=cn(e,h);a:{b:{c:{if(32<=f){var
i=f-34|0;if(58<i>>>0){if(93<=i)break c}else if(56<i-1>>>0)break b;var
j=1;break a}if(11<=f){if(13===f)break b}else if(8<=f)break b}var
j=4;break a}var
j=2}b[1]=b[1]+j|0;var
u=h+1|0;if(l===h)break;h=u}}if(b[1]===ae(e))var
k=e;else{var
c=D(b[1]);b[1]=0;var
m=ae(e)-1|0,s=0;if(m>=0){var
g=s;for(;;){var
d=cn(e,g);a:{b:{c:{if(35<=d){if(92!==d){if(bt<=d)break c;break b}}else{if(32>d){if(14<=d)break c;switch(d){case
8:r(c,b[1],92);b[1]++;r(c,b[1],98);break a;case
9:r(c,b[1],92);b[1]++;r(c,b[1],116);break a;case
10:r(c,b[1],92);b[1]++;r(c,b[1],110);break a;case
13:r(c,b[1],92);b[1]++;r(c,b[1],114);break a;default:break c}}if(34>d)break b}r(c,b[1],92);b[1]++;r(c,b[1],d);break a}r(c,b[1],92);b[1]++;r(c,b[1],48+(d/dG|0)|0);b[1]++;r(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;r(c,b[1],48+(d%10|0)|0);break a}r(c,b[1],d)}b[1]++;var
t=g+1|0;if(m===g)break;g=t}}var
k=c}var
n=e===k?a:S(k),o=A(n),p=aw(o+2|0,34);bx(n,0,p,1,o);return S(p)}function
c3(a,b){var
g=bc(b),f=gS[1];switch(a[2]){case
0:var
c=102;break;case
1:var
c=101;break;case
2:var
c=69;break;case
3:var
c=dm;break;case
4:var
c=71;break;case
5:var
c=f;break;case
6:var
c=104;break;case
7:var
c=72;break;default:var
c=70}var
d=cZ(16);aF(d,37);switch(a[1]){case
0:break;case
1:aF(d,43);break;default:aF(d,32)}if(8<=a[2])aF(d,35);aF(d,46);x(d,e+g);aF(d,c);return c1(d)}function
bg(a,b){if(13>a)return b;var
h=[0,0],i=A(b)-1|0,n=0;if(i>=0){var
d=n;for(;;){if(9>=ao(b,d)+d5>>>0)h[1]++;var
q=d+1|0;if(i===d)break;d=q}}var
j=h[1],k=D(A(b)+((j-1|0)/3|0)|0),l=[0,0];function
e(a){aB(k,l[1],a);l[1]++}var
f=[0,((j-1|0)%3|0)+1|0],m=A(b)-1|0,o=0;if(m>=0){var
c=o;for(;;){var
g=ao(b,c);if(9<g+d5>>>0)e(g);else{if(0===f[1]){e(95);f[1]=3}f[1]--;e(g)}var
p=c+1|0;if(m===c)break;c=p}}return S(k)}function
gT(a,b){switch(a){case
1:var
c=f5;break;case
2:var
c=f6;break;case
4:var
c=f8;break;case
5:var
c=f9;break;case
6:var
c=f_;break;case
7:var
c=f$;break;case
8:var
c=ga;break;case
9:var
c=gb;break;case
10:var
c=gc;break;case
11:var
c=gd;break;case
0:case
13:var
c=f4;break;case
3:case
14:var
c=f7;break;default:var
c=ge}return bg(a,bB(c,b))}function
gU(a,b){switch(a){case
1:var
c=gt;break;case
2:var
c=gu;break;case
4:var
c=gw;break;case
5:var
c=gx;break;case
6:var
c=gy;break;case
7:var
c=gz;break;case
8:var
c=gA;break;case
9:var
c=gB;break;case
10:var
c=gC;break;case
11:var
c=gD;break;case
0:case
13:var
c=gs;break;case
3:case
14:var
c=gv;break;default:var
c=gE}return bg(a,bB(c,b))}function
gV(a,b){switch(a){case
1:var
c=gG;break;case
2:var
c=gH;break;case
4:var
c=gJ;break;case
5:var
c=gK;break;case
6:var
c=gL;break;case
7:var
c=gM;break;case
8:var
c=gN;break;case
9:var
c=gO;break;case
10:var
c=gP;break;case
11:var
c=gQ;break;case
0:case
13:var
c=gF;break;case
3:case
14:var
c=gI;break;default:var
c=gR}return bg(a,bB(c,b))}function
gW(a,b){switch(a){case
1:var
c=gg;break;case
2:var
c=gh;break;case
4:var
c=gj;break;case
5:var
c=gk;break;case
6:var
c=gl;break;case
7:var
c=gm;break;case
8:var
c=gn;break;case
9:var
c=go;break;case
10:var
c=gp;break;case
11:var
c=gq;break;case
0:case
13:var
c=gf;break;case
3:case
14:var
c=gi;break;default:var
c=gr}return bg(a,iB(c,b))}function
ag(d,b,c){function
j(a){switch(d[1]){case
0:var
e=45;break;case
1:var
e=43;break;default:var
e=32}return ix(c,b,e)}function
p(a){var
b=ik(c);return 3===b?c<0.?gX:gY:4<=b?gZ:a}switch(d[2]){case
5:var
f=cq(c3(d,b),c),e=0,u=A(f);for(;;){if(e===u)var
o=0;else{var
k=O(f,e)-46|0;a:{if(23<k>>>0){if(55===k)break a}else if(21<k-1>>>0)break a;e=e+1|0;continue}var
o=1}var
v=o?f:f+az;return p(v)}case
6:return j(0);case
7:var
i=aA(j(0)),g=ae(i);if(0===g)var
n=i;else{var
l=D(g),m=g-1|0,q=0;if(m>=0){var
a=q;for(;;){var
h=cn(i,a),s=25<h+dF>>>0?h:h-32|0;r(l,a,s);var
t=a+1|0;if(m===a)break;a=t}}var
n=l}return S(n);case
8:return p(j(0));default:return cq(c3(d,b),c)}}function
aX(a,b,c,d){var
f=b,e=c,g=d;for(;;){if(typeof
g==="number")return i(f,e);switch(g[0]){case
0:var
M=g[1];return function(a){return j(f,[5,e,a],M)};case
1:var
N=g[1];return function(a){a:{b:{if(40<=a){if(92===a){var
b=fb;break a}if(bt>a)break b}else{if(32<=a){if(39>a)break b;var
b=fc;break a}if(14>a)switch(a){case
8:var
b=fd;break a;case
9:var
b=fe;break a;case
10:var
b=ff;break a;case
13:var
b=fg;break a}}var
c=D(4);r(c,0,92);r(c,1,48+(a/dG|0)|0);r(c,2,48+((a/10|0)%10|0)|0);r(c,3,48+(a%10|0)|0);var
b=S(c);break a}var
d=D(1);r(d,0,a);var
b=S(d)}var
g=A(b),h=aw(g+2|0,39);bx(b,0,h,1,g);return j(f,[4,e,S(h)],N)};case
2:return bP(f,e,g[2],g[1],function(a){return a});case
3:return bP(f,e,g[2],g[1],f3);case
4:return bh(f,e,g[4],g[2],g[3],gT,g[1]);case
5:return bh(f,e,g[4],g[2],g[3],gU,g[1]);case
6:return bh(f,e,g[4],g[2],g[3],gV,g[1]);case
7:return bh(f,e,g[4],g[2],g[3],gW,g[1]);case
8:var
u=g[4],w=g[3],x=g[2],t=g[1];if(typeof
x==="number"){if(typeof
w==="number")return w?function(a,b){return j(f,[4,e,ag(t,a,b)],u)}:function(a){return j(f,[4,e,ag(t,bN(t),a)],u)};var
_=w[1];return function(a){return j(f,[4,e,ag(t,_,a)],u)}}if(0===x[0]){var
B=x[2],C=x[1];if(typeof
w==="number")return w?function(a,b){return j(f,[4,e,K(C,B,ag(t,a,b))],u)}:function(a){return j(f,[4,e,K(C,B,ag(t,bN(t),a))],u)};var
$=w[1];return function(a){return j(f,[4,e,K(C,B,ag(t,$,a))],u)}}var
E=x[1];if(typeof
w==="number")return w?function(a,b,c){return j(f,[4,e,K(E,a,ag(t,b,c))],u)}:function(a,b){return j(f,[4,e,K(E,a,ag(t,bN(t),b))],u)};var
aa=w[1];return function(a,b){return j(f,[4,e,K(E,a,ag(t,aa,b))],u)};case
9:return bP(f,e,g[2],g[1],e8);case
10:e=[7,e];g=g[1];break;case
11:e=[2,e,g[1]];g=g[2];break;case
12:e=[3,e,g[1]];g=g[2];break;case
13:var
O=g[3],P=g[2],F=cZ(16);bO(F,P);var
L=c1(F);return function(a){return j(f,[4,e,L],O)};case
14:var
R=g[3],T=g[2];return function(a){var
c=a[1],b=m(c,p(s(T)));if(typeof
b[2]==="number")return j(f,e,o(b[1],R));throw h(v,1)};case
15:var
U=g[1];return function(c,b){return j(f,[6,e,function(a){return Q(c,a,b)}],U)};case
16:var
V=g[1];return function(a){return j(f,[6,e,a],V)};case
17:e=[0,e,g[1]];g=g[2];break;case
18:var
z=g[1];if(0===z[0]){let
b=e,c=f,d=g[2];f=function(a){return j(c,[1,b,[0,a]],d)};e=0;g=z[1][1]}else{let
b=e,c=f,d=g[2];f=function(a){return j(c,[1,b,[1,a]],d)};e=0;g=z[1][1]}break;case
19:throw h([0,q,g1],1);case
20:var
W=g[3],X=[8,e,g2];return function(a){return j(f,X,W)};case
21:var
Y=g[2];return function(a){return j(f,[4,e,bB(dZ,a)],Y)};case
22:var
Z=g[1];return function(a){return j(f,[5,e,a],Z)};case
23:var
k=g[2],y=g[1];if(typeof
y==="number")switch(y){case
0:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
1:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
2:throw h([0,q,g3],1);default:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k])}switch(y[0]){case
0:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
1:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
2:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
3:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
4:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
5:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
6:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
7:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
8:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);case
9:var
J=y[2];return a<50?b3(a+1|0,f,e,J,k):n(b3,[0,f,e,J,k]);case
10:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k]);default:return a<50?l(a+1|0,f,e,k):n(l,[0,f,e,k])}default:var
G=g[3],H=g[1],I=i(g[2],0);return a<50?b2(a+1|0,f,e,G,H,I):n(b2,[0,f,e,G,H,I])}}}function
j(a,b,c){return ba(aX(0,a,b,c))}function
b3(a,f,c,d,e){if(typeof
d==="number")return a<50?l(a+1|0,f,c,e):n(l,[0,f,c,e]);switch(d[0]){case
0:var
b=d[1];return function(a){return P(f,c,b,e)};case
1:var
g=d[1];return function(a){return P(f,c,g,e)};case
2:var
i=d[1];return function(a){return P(f,c,i,e)};case
3:var
j=d[1];return function(a){return P(f,c,j,e)};case
4:var
k=d[1];return function(a){return P(f,c,k,e)};case
5:var
m=d[1];return function(a){return P(f,c,m,e)};case
6:var
o=d[1];return function(a){return P(f,c,o,e)};case
7:var
p=d[1];return function(a){return P(f,c,p,e)};case
8:var
r=d[2];return function(a){return P(f,c,r,e)};case
9:var
u=d[3],v=d[2],w=t(s(d[1]),v);return function(a){return P(f,c,E(w,u),e)};case
10:var
x=d[1];return function(a,b){return P(f,c,x,e)};case
11:var
y=d[1];return function(a){return P(f,c,y,e)};case
12:var
z=d[1];return function(a){return P(f,c,z,e)};case
13:throw h([0,q,g4],1);default:throw h([0,q,g5],1)}}function
P(a,b,c,d){return ba(b3(0,a,b,c,d))}function
l(a,b,c,d){var
e=[8,c,g6];return a<50?aX(a+1|0,b,e,d):n(aX,[0,b,e,d])}function
bP(g,f,c,d,e){if(typeof
d==="number")return function(a){return j(g,[4,f,i(e,a)],c)};if(0===d[0]){var
b=d[2],h=d[1];return function(a){return j(g,[4,f,K(h,b,i(e,a))],c)}}var
k=d[1];return function(a,b){return j(g,[4,f,K(k,a,i(e,b))],c)}}function
bh(k,i,h,d,e,f,g){if(typeof
d==="number"){if(typeof
e==="number")return e?function(a,b){return j(k,[4,i,aG(a,Q(f,g,b))],h)}:function(a){return j(k,[4,i,Q(f,g,a)],h)};var
b=e[1];return function(a){return j(k,[4,i,aG(b,Q(f,g,a))],h)}}if(0===d[0]){var
c=d[2],l=d[1];if(typeof
e==="number")return e?function(a,b){return j(k,[4,i,K(l,c,aG(a,Q(f,g,b)))],h)}:function(a){return j(k,[4,i,K(l,c,Q(f,g,a))],h)};var
n=e[1];return function(a){return j(k,[4,i,K(l,c,aG(n,Q(f,g,a)))],h)}}var
m=d[1];if(typeof
e==="number")return e?function(a,b,c){return j(k,[4,i,K(m,a,aG(b,Q(f,g,c)))],h)}:function(a,b){return j(k,[4,i,K(m,a,Q(f,g,b))],h)};var
o=e[1];return function(a,b){return j(k,[4,i,K(m,a,aG(o,Q(f,g,b)))],h)}}function
b2(a,b,c,d,e,f){if(e){var
h=e[1];return function(a){return g0(b,c,d,h,i(f,a))}}var
g=[4,c,f];return a<50?aX(a+1|0,b,g,d):n(aX,[0,b,g,d])}function
g0(a,b,c,d,e){return ba(b2(0,a,b,c,d,e))}function
ah(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
f=c[1],g=c2(c[2]);ah(a,f);return av(a,g);case
1:var
d=c[2],e=c[1];if(0===d[0]){var
h=d[1];ah(a,e);av(a,g7);c=h}else{var
j=d[1];ah(a,e);av(a,g8);c=j}break;case
6:var
m=c[2];ah(a,c[1]);return i(m,a);case
7:ah(a,c[1]);af(a);return;case
8:var
n=c[2];ah(a,c[1]);return Z(n);case
2:case
4:var
k=c[2];ah(a,c[1]);return av(a,k);default:var
l=c[2];ah(a,c[1]);cE(a,l);return}}}function
ap(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
k=c[1],l=c2(c[2]);ap(a,k);return aV(a,l);case
1:var
e=c[2],g=c[1];if(0===e[0]){var
m=e[1];ap(a,g);aV(a,g9);c=m}else{var
n=e[1];ap(a,g);aV(a,g_);c=n}break;case
6:var
p=c[2];ap(a,c[1]);return aV(a,i(p,0));case
7:c=c[1];break;case
8:var
q=c[2];ap(a,c[1]);return Z(q);case
2:case
4:var
o=c[2];ap(a,c[1]);return aV(a,o);default:var
h=c[2];ap(a,c[1]);var
d=a[2],f=a[1],j=f[1];if(f[2]<=d){cW(a,1);aB(a[1][1],a[2],h)}else
r(j,d,h);a[2]=d+1|0;return}}}function
bi(c,b){return j(function(a){ah(c,a);return 0},0,b[1])}function
bQ(e,b){return j(function(a){var
f=64,c=aU<64?aU:f,d=D(c),b=[0,[0,d,c],0,d];ap(b,a);return i(e,cT(b[1][1],0,b[2]))},0,b[1])}function
T(a){return bQ(function(a){return a},a)}var
b1=[0,0],g$=[0,[3,0,0],"%S"],ha=ec,hb=[0,[4,0,0,0,0],b5],hc=e,hd=[0,[11,b_,[2,0,[2,0,0]]],", %s%s"],he=[0,[12,40,[2,0,[2,0,[12,41,0]]]],"(%s%s)"],hf=e,hg=e,hh=[0,[12,40,[2,0,[12,41,0]]],"(%s)"],hi="Out of memory",hj="Stack overflow",hk="Pattern matching failed",hl="Assertion failed",hm="Undefined recursive module",hn="Raised at",ho="Re-raised at",hp="Raised by primitive operation at",hq="Called from",hr=[0,[12,32,[4,0,0,0,0]]," %d"],hs=" (inlined)",ht=[0,[2,0,[12,32,[2,0,[11,' in file "',[2,0,[12,34,[2,0,[11,", line",[2,0,[11,ek,h_]]]]]]]]]],'%s %s in file "%s"%s, line%s, characters %d-%d'],hu=e,hv=[0,[11,"s ",[4,0,0,0,[12,45,[4,0,0,0,0]]]],"s %d-%d"],hw=[0,[2,0,[11," unknown location",0]],"%s unknown location"],hx=[0,[2,0,[12,10,0]],"%s\n"];function
bS(a,b){var
c=a[1+b];if(!(1-(typeof
c==="number"?1:0)))return i(T(hb),c);if(bH(c)===bl)return i(T(g$),c);if(bH(c)!==253)return ha;var
e=cq("%.12g",c),d=0,g=A(e);for(;;){if(g<=d)return e+az;var
f=O(e,d);a:{if(48<=f){if(58>f)break a}else if(45===f)break a;return e}d=d+1|0}}function
c4(a,b){if(a.length-1<=b)return hc;var
c=c4(a,b+1|0),d=bS(a,b);return Q(T(hd),d,c)}function
aH(a){a:{b:{var
b=bv(b1);for(;;){if(!b)break;c:{var
u=b[2],v=b[1];try{var
k=i(v,a)}catch(f){break c}if(k)break b}b=u}var
h=0;break a}var
h=[0,k[1]]}if(h)return h[1];if(a===bM)return hi;if(a===cO)return hj;if(a[1]===cN){var
e=a[2],n=e[3],x=e[2],y=e[1];return b4(T(bR),y,x,n,n+5|0,hk)}if(a[1]===q){var
f=a[2],o=f[3],z=f[2],A=f[1];return b4(T(bR),A,z,o,o+6|0,hl)}if(a[1]===cQ){var
g=a[2],p=g[3],B=g[2],C=g[1];return b4(T(bR),C,B,p,p+6|0,hm)}if(0===bH(a)){var
j=a.length-1,w=a[1][1];if(2<j>>>0)var
r=c4(a,2),s=bS(a,1),c=Q(T(he),s,r);else
switch(j){case
0:var
c=hf;break;case
1:var
c=hg;break;default:var
t=bS(a,1),c=i(T(hh),t)}var
d=[0,w,[0,c]]}else
var
d=[0,a[1],0];var
l=d[2],m=d[1];return l?m+l[1]:m}function
bj(a,b){var
f=im(b),j=f.length-2|0,u=0;if(j>=0){var
d=u;for(;;){var
c=a5(f,d)[1+d];let
b=d;var
g=function(a){return a?0===b?hn:ho:0===b?hp:hq};if(0===c[0]){if(c[3]===c[6])var
k=c[3],h=i(T(hr),k);else
var
r=c[6],s=c[3],h=Q(T(hv),s,r);var
l=c[7],m=c[4],n=c[8]?hs:hu,o=c[2],p=c[9],q=g(c[1]),e=[0,h$(T(ht),q,p,o,n,h,m,l)]}else if(c[1])var
e=0;else
var
t=g(0),e=[0,i(T(hw),t)];if(e){var
v=e[1];i(bi(a,hx),v)}var
w=d+1|0;if(j===d)break;d=w}}return 0}function
c5(a){return bj(a,cr(0))}function
c6(a){for(;;){var
c=bv(b1),b=1-et(b1,c,[0,a,c]);if(!b)return b}}var
hy=[0,e,"(Cannot print locations:\n bytecode executable program file not found)","(Cannot print locations:\n bytecode executable program file appears to be corrupt)","(Cannot print locations:\n bytecode executable program file has wrong magic number)","(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)"].slice(),hz=[0,[11,br,[2,0,[12,10,0]]],d1],hA=[0],hB="Fatal error: out of memory in uncaught exception handler",hC=[0,[11,br,[2,0,[12,10,0]]],d1],hD=[0,[11,"Fatal error in uncaught exception handler: exception ",[2,0,[12,10,0]]],"Fatal error in uncaught exception handler: exception %s\n"];cG(ef,function(a,b){try{try{var
g=b?hA:cr(0);try{bd(0)}catch(f){}try{var
f=aH(a);i(bi(B,hz),f);bj(B,g);var
c=iX(0);if(c<0){var
d=bc(c);cR(a5(hy,d)[1+d])}var
o=af(B),j=o}catch(f){var
l=aE(f),m=aH(a);i(bi(B,hC),m);bj(B,g);var
n=aH(l);i(bi(B,hD),n);bj(B,cr(0));var
j=af(B)}var
k=j}catch(f){var
e=aE(f);if(e!==bM)throw h(e,0);var
k=cR(hB)}return k}catch(f){return 0}});var
hE=[g,"Stdlib.Fun.Finally_raised",a7(0)];c6(function(a){return a[1]===hE?[0,"Fun.Finally_raised: "+aH(a[2])]:0});var
hF="Digest.BLAKE2: wrong hash size";function
bT(a){var
b=a[1]<1?1:0,c=b||(64<a[1]?1:0);if(c)Z(hF)}bT([0,16]);bT([0,32]);bT([0,64]);var
hG=R(1,0,0),hH=R(0,0,0),hI=R(0,0,0),hJ=R(2,0,0),hK=R(1,0,0);function
c7(a,b,c,d){var
e=ic(7,0,[0,4]);a4(e,0,eN(a,hG));a4(e,1,b);var
f=aD(c,hH)?c:hK;a4(e,2,f);var
g=aD(d,hI)?d:hJ;a4(e,3,g);return e}var
hL=R(14371852,15349651,22696),hM=R(12230193,11438743,35013),hN=R(1424933,15549263,2083),hO=R(9492471,4696708,43520);cX([0,function(a){var
b=bF(a),d=bF(a),c=bF(a);return c7(b,d,c,bF(a))}],function(a){return c7(hO,hN,hM,hL)});function
aa(a){var
c=a[1];switch(c[0]){case
0:return a;case
1:return a;case
2:return a;default:var
d=c[1],b=aa(d);if(1-(b===d?1:0))a[1]=[3,b];return b}}var
aq=[0,0],hQ=br;function
c8(a,b){return typeof
a==="number"?b:typeof
b==="number"?a:[0,a,b]}function
bV(a){if(typeof
a!=="number")switch(a[0]){case
0:var
b=a[2],c=bV(a[1]);return c8(c,bV(b));case
2:if(!a[1][1])return 0;break}return a}function
c9(a,b){var
d=[1,b],c=a[1],e=typeof
c==="number"?d:[0,d,c];a[1]=e}var
c_=[0,function(a){av(B,hQ);av(B,aH(a));cE(B,10);c5(B);af(B);bd(0);return i_(2)}];function
bW(a,b){try{var
d=i(a,b);return d}catch(f){var
c=aE(f);return i(c_[1],c)}}var
bX=[g,"Lwt.Resolution_loop.Canceled",a7(0)];function
c$(a,h){if(1===h[0])var
f=h[1]===bX?1:0,b=f;else
var
b=0;if(b){var
d=function(a,b,c){var
e=b,d=c;for(;;){if(typeof
e==="number")return a<50?g(a+1|0,d):n(g,[0,d]);switch(e[0]){case
0:var
h=[0,e[2],d];e=e[1];d=h;break;case
1:var
i=e[2];aq[1]=e[1];bW(i,0);return a<50?g(a+1|0,d):n(g,[0,d]);default:var
f=e[1];if(f[4]){f[4]=0;f[1][2]=f[2];f[2][1]=f[1]}return a<50?g(a+1|0,d):n(g,[0,d])}}},g=function(a,b){if(!b)return;var
c=b[2],e=b[1];return a<50?d(a+1|0,e,c):n(d,[0,e,c])};(function(a,b){return ba(d(0,a,b))}(a[2],0))}function
c(a,b,c){var
f=b,d=c;for(;;){if(typeof
f==="number")return a<50?e(a+1|0,d):n(e,[0,d]);switch(f[0]){case
0:var
j=[0,f[2],d];f=f[1];d=j;break;case
1:i(f[1],h);return a<50?e(a+1|0,d):n(e,[0,d]);default:var
g=f[1][1];return g?(i(g[1],h),a<50?e(a+1|0,d):n(e,[0,d])):a<50?e(a+1|0,d):n(e,[0,d])}}}function
e(a,b){if(!b)return 0;var
d=b[2],e=b[1];return a<50?c(a+1|0,e,d):n(c,[0,e,d])}return function(a,b){return ba(c(0,a,b))}(a[1],0)}var
ax=[0,0],$=[0,0,0,0],fl=[g,"Stdlib.Queue.Empty",a7(0)],hR=42;function
da(a){ax[1]=ax[1]+1|0;var
e=aq[1],f=i(a,0);if(1===ax[1])for(;;){if(0===$[1])break;var
b=$[2];if(!b)throw h(fl,1);var
c=b[1];if(b[2]){var
d=b[2];$[1]=$[1]-1|0;$[2]=d}else{$[1]=0;$[2]=0;$[3]=0}c$(c[1],c[2])}ax[1]=ax[1]-1|0;aq[1]=e;return f}function
aI(a,b,c,d){var
f=c[1][1];c[1]=d;var
e=a?a[1]:1,g=b?b[1]:hR,h=e?g<=ax[1]?1:0:e;if(h)cV([0,f,d],$);else
da(function(a){return c$(f,d)});return c}function
bY(a,b,c){var
e=a?a[1]:0;if(e)return i(b,0);if(42>ax[1])return da(function(a){return i(b,0)});var
d=i(c,0),f=d[1];cV([0,[0,[1,d[2]],0,0,0],d[3]],$);return f}var
dc=[0,[0,0]],hZ=[0,0],h0=[0,0],h1=[0,1];function
bZ(a){return[0,[2,[0,0,0,a,0]]]}function
dd(d,b){var
c=aa(b);function
e(a){var
b=bZ([0,c]),f=aq[1];return[0,b,function(a){if(1===a[0]){aI(h0,0,aa(b),a);return 0}var
g=a[1];aq[1]=f;try{var
j=[0,i(d,g)],e=j}catch(f){var
c=aE(f);if(!1)throw h(c,0);var
e=[1,c]}aI(hZ,0,aa(b),e);return 0}]}var
a=c[1];switch(a[0]){case
1:return[0,a];case
2:var
j=a[1],f=e(0),k=f[1];c9(j,f[2]);return k;default:var
g=a[1];return bY(h1,function(a){try{var
e=[0,i(d,g)],c=e}catch(f){var
b=aE(f);if(!1)throw h(b,0);var
c=[1,b]}return[0,c]},function(a){var
b=e(0);return[0,b[1],b[2],c[1]]})}}var
bU=[];ja(bU,[0,bU,bU]);var
de=[g,"Jsoo_runtime.Error.Exn",a7(0)],b0=[0,de,[0]],h2=[0,0],h3=[0,1],hX=[0,0],hY=[0,1],hV=[0,0],hW=[0,0],hS=[0,[11,d2,[2,0,0]],dt],hT=[0,[11,d2,[2,0,0]],dt],hU=[0,0],h7="Exception during Lwt.async: ",h8="nightmare_js",h9="capsule_hljs",hP=bH(b0)===g?b0:b0[1];cG(cd,hP);(function(a){throw a});var
C=c,df=null;C.String;C.RegExp;C.Object;C.Array;C.Date;C.Math;function
dg(a){return F(a.toString())}C.JSON;var
h5=C.Error;c6(function(a){return a
instanceof
h5?[0,dg(a)]:a[1]===de?[0,dg(a[2])]:0});function
dh(a,b){a:{var
d=bE(a);if(F(typeof
b)==="function"&&0<b.length){var
c=cB(b);break a}var
c=b}jc[d]=c}C.document;C.HTMLElement;var
h6=iR(0);function
di(a){h6.log(bE(a))}c_[1]=function(a){di(h7);di(aH(a));return c5(B)};function
dj(a,b){return b?[0,i(a,b[1])]:0}C.document;var
h4=undefined;dh(h8,{nightmare:{suspending:cA([0])},suspend:cC(function(a,b){a.nightmare.suspending.push(b);return 0}),mount:cC(function(a){var
y=iS(a.nightmare.suspending),f=[0,function(a){return dc}],n=y.length-2|0,z=0;if(n>=0){var
b=z;for(;;){let
c=y[1+b],d=f[1];f[1]=function(a){return dd(function(a){return c()},i(d,0))};var
B=b+1|0;if(n===b)break;b=B}}var
A=f[1];function
x(a){return dd(function(a){return 0},i(A,0))}var
t=[0,df],g=bZ(1);function
e(a){var
c=t[1],b=1-(c==df?1:0);return b?i(c,0):b}var
k=aa(g)[1],H=0,I=0;switch(k[0]){case
1:if(k[1]===bX)bY(h3,function(a){return bW(e,0)},function(a){return[0,0,function(a){return bW(e,0)},h2]});break;case
2:var
l=k[1],o=[1,aq[1],e],D=typeof
l[2]==="number"?o:[0,o,l[2]];l[2]=D;break}var
m=iT(function(a){e(0);var
b=[0,a],c=aa(g),d=c[1];switch(d[0]){case
1:if(d[1]!==bX)i(bQ(Z,hT),db);break;case
2:var
h=0===b[0]?[0,b[1]]:[1,b[1]];aI(hU,0,c,h);break;default:i(bQ(Z,hS),db)}var
f=!!1;if(1-(f|0))a.preventDefault();return f}),u=dj(eO,H),v=dj(eO,I);if(1-(C.addEventListener===h4?1:0)){var
d={};if(v)d.capture=v[1];if(u)d.passive=u[1];C.addEventListener(b7,m,d);var
w=function(a){return C.removeEventListener(b7,m,d)}}else{var
r="on".concat(b7),s=function(a){var
c=[0,m,a,[0]];return function(a,b){return iP(c,a,b)}};C.attachEvent(r,s);var
w=function(a){return C.detachEvent(r,s)}}t[1]=w;var
j=aa(g);function
p(a){var
i=bZ([0,j]),r=aq[1];return[0,i,function(a){if(1===a[0]){aI(hX,0,aa(i),a);return 0}var
s=a[1];aq[1]=r;try{var
t=x(s),p=t}catch(f){var
o=aE(f);if(!1)throw h(o,0);var
p=[0,[1,o]]}var
d=aa(i),c=aa(p);if(c!==d){var
n=c[1];switch(n[0]){case
1:aI(hW,0,d,c[1]);break;case
2:var
e=n[1],b=d[1][1],j=c8(b[1],e[1]),k=b[4]+e[4]|0;if(42<k)var
m=0,l=bV(j);else
var
m=k,l=j;var
f=e[2],g=b[2],q=typeof
g==="number"?f:typeof
f==="number"?g:[0,g,f];b[1]=l;b[2]=q;b[4]=m;b[3]=e[3];c[1]=[3,d];break;default:aI(hV,0,d,c[1])}}return 0}]}var
c=j[1];switch(c[0]){case
1:return[0,c];case
2:var
F=c[1],q=p(0),G=q[1];c9(F,q[2]);return G;default:var
E=c[1];return bY(hY,function(a){return x(E)},function(a){var
b=p(0);return[0,b[1],b[2],j[1]]})}})});dh(h9,{run:cC(function(a){C.hljs.highlightAll();return dc})});bd(0);return}(globalThis));
